// <auto-generated/>

namespace Internal.Generated.WolverineHandlers

open System
open System.Threading
open System.Threading.Tasks
open Wolverine.Runtime
open Wolverine.Runtime.Handlers

type BehaviouralPingHandler1244766258() =
    inherit Wolverine.Runtime.Handlers.MessageHandler()
    override this.HandleAsync(_context: Wolverine.Runtime.MessageContext, _cancellation: System.Threading.CancellationToken) : System.Threading.Tasks.Task =
        // The actual message body
        let behaviouralPing = _context.Envelope.Message :?> WolverineBehaviouralFSharpApp.BehaviouralPing

        if not (isNull System.Diagnostics.Activity.Current) then
            System.Diagnostics.Activity.Current.SetTag("message.handler", "WolverineBehaviouralFSharpApp.BehaviouralPingHandler") |> ignore
            System.Diagnostics.Activity.Current.SetTag("handler.type", "WolverineBehaviouralFSharpApp.BehaviouralPingHandler") |> ignore
        
        // The actual message execution
        WolverineBehaviouralFSharpApp.BehaviouralPingHandler.Handle(behaviouralPing)

        System.Threading.Tasks.Task.CompletedTask

