<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>Amazon S3 integration for Wolverine, including the claim check store for large message payloads</Description>
        <PackageId>WolverineFx.AmazonS3</PackageId>
        <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
        <GenerateAssemblyCopyrightAttribute>false</GenerateAssemblyCopyrightAttribute>
        <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
        <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
        <GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Wolverine\Wolverine.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AWSSDK.S3" />
    </ItemGroup>

</Project>
