// <auto-generated/>

namespace Internal.Generated.WolverineHandlers

open Microsoft.Extensions.DependencyInjection
open System
open System.Collections.Generic
open System.Threading
open System.Threading.Tasks
open Wolverine.Runtime
open Wolverine.Runtime.Handlers

type CreateItemCommandHandler670389475(serviceScopeFactory: Microsoft.Extensions.DependencyInjection.IServiceScopeFactory, domainEventScraperIEnumerable: System.Collections.Generic.IEnumerable<Wolverine.EntityFrameworkCore.IDomainEventScraper>) =
    inherit Wolverine.Runtime.Handlers.MessageHandler()
    let _serviceScopeFactory = serviceScopeFactory
    let _domainEventScraperIEnumerable = domainEventScraperIEnumerable

    override this.HandleAsync(context: Wolverine.Runtime.MessageContext, cancellation: System.Threading.CancellationToken) : System.Threading.Tasks.Task =
        task {
            use serviceScope = Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.CreateAsyncScope(_serviceScopeFactory)
            // This service has been marked as requiring service location independent of Wolverine's ability to use constructor injection of everything else
            let itemsDbContext = Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<WolverineFSharpSample.ItemsDbContext>(serviceScope.ServiceProvider)
            // The actual message body
            let createItemCommand = context.Envelope.Message :?> WolverineFSharpSample.CreateItemCommand


            // Enroll the DbContext & IMessagingContext in the outgoing Wolverine outbox transaction
            let efCoreEnvelopeTransaction = Wolverine.EntityFrameworkCore.Internals.EfCoreEnvelopeTransaction(itemsDbContext, context, _domainEventScraperIEnumerable)
            do! context.EnlistInOutboxAsync(efCoreEnvelopeTransaction)
            // Start the actual database transaction if one does not already exist
            if isNull itemsDbContext.Database.CurrentTransaction then
                let! _ = itemsDbContext.Database.BeginTransactionAsync(cancellation)
                ()
            try
                if not (isNull System.Diagnostics.Activity.Current) then
                    System.Diagnostics.Activity.Current.SetTag("message.handler", "WolverineFSharpSample.CreateItemHandler") |> ignore
                    System.Diagnostics.Activity.Current.SetTag("handler.type", "WolverineFSharpSample.CreateItemHandler") |> ignore
                
                // The actual message execution
                let outgoing1 = WolverineFSharpSample.CreateItemHandler.Handle(createItemCommand, itemsDbContext)

                
                // Outgoing, cascaded message
                do! context.EnqueueCascadingAsync(outgoing1)

                
                // Added by EF Core Transaction Middleware
                let! result_of_SaveChangesAsync = itemsDbContext.SaveChangesAsync(cancellation)

                // Commit the EF Core transaction and flush outgoing messages before writing the response (GH-2917)
                do! efCoreEnvelopeTransaction.CommitAsync(cancellation)
            with ex ->
                do! efCoreEnvelopeTransaction.RollbackAsync()
                System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(ex).Throw()
        }

