// <auto-generated/>

namespace Wolverine.Core.FSharpFixture.Generated

open System
open Wolverine.Core.FSharpContracts
open Wolverine.Runtime

type GeneratedFoundationProbe() =
    interface Wolverine.Core.FSharpContracts.IFoundationProbe with
        member _.Run(runtime: Wolverine.Runtime.IWolverineRuntime) : unit =
            // Generated by Wolverine F# code generation (GH-2969 foundation probe)
            let messageContext = Wolverine.Runtime.MessageContext(runtime)
            ()

