// <auto-generated/>

namespace Internal.Generated.WolverineHandlers

open Microsoft.Extensions.Logging
open System
open System.Threading
open System.Threading.Tasks
open Wolverine.Persistence.Sagas
open Wolverine.Runtime
open Wolverine.Runtime.Handlers

type CheckThingHandler649476295(loggerForMessage: Microsoft.Extensions.Logging.ILogger<Wolverine.Core.FSharpContracts.CheckThing>) =
    inherit Wolverine.Runtime.Handlers.MessageHandler()
    let _loggerForMessage = loggerForMessage

    override this.HandleAsync(context: Wolverine.Runtime.MessageContext, _cancellation: System.Threading.CancellationToken) : System.Threading.Tasks.Task =
        // The actual message body
        let checkThing = context.Envelope.Message :?> Wolverine.Core.FSharpContracts.CheckThing

        Wolverine.Runtime.WolverineTracing.ApplyExecutionDiagnosticTags(System.Diagnostics.Activity.Current, context.Envelope)
        if not (isNull System.Diagnostics.Activity.Current) then
            System.Diagnostics.Activity.Current.SetTag("message.handler", "Wolverine.Core.FSharpContracts.CheckThingHandler") |> ignore
            System.Diagnostics.Activity.Current.SetTag("handler.type", "Wolverine.Core.FSharpContracts.CheckThingHandler") |> ignore
        let checkThingHandler = Wolverine.Core.FSharpContracts.CheckThingHandler()
        let requirementResult1 = checkThingHandler.Before(checkThing)
        // Check RequirementResult and abort if Branch == Stop
        if Wolverine.Middleware.RequirementResultContinuationPolicy.ShouldStop((_loggerForMessage :> Microsoft.Extensions.Logging.ILogger), requirementResult1) then
            ()
        else
            
            // The actual message execution
            checkThingHandler.Handle(checkThing)

            this.RecordCauseAndEffect(context, context.Runtime.Observer)
        System.Threading.Tasks.Task.CompletedTask

type CreateNameHandler1923366998(loggerForMessage: Microsoft.Extensions.Logging.ILogger<Wolverine.Core.FSharpContracts.CreateName>) =
    inherit Wolverine.Runtime.Handlers.MessageHandler()
    let _loggerForMessage = loggerForMessage

    override this.HandleAsync(context: Wolverine.Runtime.MessageContext, _cancellation: System.Threading.CancellationToken) : System.Threading.Tasks.Task =
        task {
            // The actual message body
            let createName = context.Envelope.Message :?> Wolverine.Core.FSharpContracts.CreateName

            Wolverine.Runtime.WolverineTracing.ApplyExecutionDiagnosticTags(System.Diagnostics.Activity.Current, context.Envelope)
            // Application-specific Open Telemetry auditing
            if not (isNull System.Diagnostics.Activity.Current) then
                System.Diagnostics.Activity.Current.SetTag("name", createName.Name) |> ignore
            if not (isNull System.Diagnostics.Activity.Current) then
                System.Diagnostics.Activity.Current.SetTag("message.handler", "Wolverine.Core.FSharpContracts.NameHandler") |> ignore
                System.Diagnostics.Activity.Current.SetTag("handler.type", "Wolverine.Core.FSharpContracts.NameHandler") |> ignore
            let nameHandler = Wolverine.Core.FSharpContracts.NameHandler()
            let stringValueIEnumerable1 = nameHandler.Validate(createName)
            // Check for any simple validation messages and abort if any exist
            if Wolverine.Middleware.SimpleValidationContinuationPolicy.LogValidationMessages((_loggerForMessage :> Microsoft.Extensions.Logging.ILogger), stringValueIEnumerable1) then
                ()
            else
                
                // The actual message execution
                let outgoing1 = nameHandler.Handle(createName)

                
                // Outgoing, cascaded message
                do! context.EnqueueCascadingAsync(outgoing1)

                this.RecordCauseAndEffect(context, context.Runtime.Observer)
        }

type GateHandler1696712162() =
    inherit Wolverine.Runtime.Handlers.MessageHandler()
    override this.HandleAsync(context: Wolverine.Runtime.MessageContext, _cancellation: System.Threading.CancellationToken) : System.Threading.Tasks.Task =
        // The actual message body
        let gate = context.Envelope.Message :?> Wolverine.Core.FSharpContracts.Gate

        Wolverine.Runtime.WolverineTracing.ApplyExecutionDiagnosticTags(System.Diagnostics.Activity.Current, context.Envelope)
        if not (isNull System.Diagnostics.Activity.Current) then
            System.Diagnostics.Activity.Current.SetTag("message.handler", "Wolverine.Core.FSharpContracts.GateHandler") |> ignore
            System.Diagnostics.Activity.Current.SetTag("handler.type", "Wolverine.Core.FSharpContracts.GateHandler") |> ignore
        let gateHandler = Wolverine.Core.FSharpContracts.GateHandler()
        let result_of_Before1 = gateHandler.Before(gate)
        // Evaluate whether or not the execution should stop based on the HandlerContinuation value
        if result_of_Before1 = Wolverine.HandlerContinuation.Stop then
            ()
        else
            
            // The actual message execution
            gateHandler.Handle(gate)

            this.RecordCauseAndEffect(context, context.Runtime.Observer)
        System.Threading.Tasks.Task.CompletedTask

type IncrementCountHandler540640831(inMemorySagaPersistor: Wolverine.Persistence.Sagas.InMemorySagaPersistor) =
    inherit Wolverine.Runtime.Handlers.MessageHandler()
    let _inMemorySagaPersistor = inMemorySagaPersistor

    override this.HandleAsync(context: Wolverine.Runtime.MessageContext, _cancellation: System.Threading.CancellationToken) : System.Threading.Tasks.Task =
        // The actual message body
        let incrementCount = context.Envelope.Message :?> Wolverine.Core.FSharpContracts.IncrementCount

        // Application-specific Open Telemetry auditing
        if not (isNull System.Diagnostics.Activity.Current) then
            System.Diagnostics.Activity.Current.SetTag("Id", incrementCount.Id) |> ignore
        let sagaId = if isNull incrementCount.Id then context.Envelope.SagaId else incrementCount.Id
        if System.String.IsNullOrEmpty(sagaId) then
            raise (Wolverine.Persistence.Sagas.IndeterminateSagaStateIdException(context.Envelope))
        let countingSaga = _inMemorySagaPersistor.Load<Wolverine.Core.FSharpContracts.CountingSaga>(sagaId)
        if isNull (box countingSaga) then
            raise (Wolverine.Persistence.Sagas.UnknownSagaException(typeof<Wolverine.Core.FSharpContracts.CountingSaga>, sagaId))
        else
            context.SetSagaId(sagaId)
            if not (isNull System.Diagnostics.Activity.Current) then
                System.Diagnostics.Activity.Current.SetTag("wolverine.saga.id", sagaId.ToString()) |> ignore
                System.Diagnostics.Activity.Current.SetTag("wolverine.saga.type", "Wolverine.Core.FSharpContracts.CountingSaga") |> ignore
            
            // The actual message execution
            countingSaga.Handle(incrementCount)

            // Delete the saga if completed, otherwise update it
            if countingSaga.IsCompleted() then
                _inMemorySagaPersistor.Delete<Wolverine.Core.FSharpContracts.CountingSaga>(sagaId)
            else
                _inMemorySagaPersistor.Store<Wolverine.Core.FSharpContracts.CountingSaga>(countingSaga)
            // No unit of work
        System.Threading.Tasks.Task.CompletedTask

type StartCountHandler1561563330(inMemorySagaPersistor: Wolverine.Persistence.Sagas.InMemorySagaPersistor) =
    inherit Wolverine.Runtime.Handlers.MessageHandler()
    let _inMemorySagaPersistor = inMemorySagaPersistor

    override this.HandleAsync(context: Wolverine.Runtime.MessageContext, _cancellation: System.Threading.CancellationToken) : System.Threading.Tasks.Task =
        // The actual message body
        let startCount = context.Envelope.Message :?> Wolverine.Core.FSharpContracts.StartCount

        // Application-specific Open Telemetry auditing
        if not (isNull System.Diagnostics.Activity.Current) then
            System.Diagnostics.Activity.Current.SetTag("Id", startCount.Id) |> ignore
        
        // The actual message execution
        let outgoing1 = Wolverine.Core.FSharpContracts.CountingSaga.Start(startCount)

        context.SetSagaId(startCount.Id)
        if not (isNull System.Diagnostics.Activity.Current) then
            System.Diagnostics.Activity.Current.SetTag("wolverine.saga.id", startCount.Id.ToString()) |> ignore
            System.Diagnostics.Activity.Current.SetTag("wolverine.saga.type", "Wolverine.Core.FSharpContracts.CountingSaga") |> ignore
        if not (outgoing1.IsCompleted()) then
            _inMemorySagaPersistor.Store<Wolverine.Core.FSharpContracts.CountingSaga>(outgoing1)
        // No unit of work
        System.Threading.Tasks.Task.CompletedTask

type TickHandler1778389912() =
    inherit Wolverine.Runtime.Handlers.MessageHandler()
    override this.HandleAsync(context: Wolverine.Runtime.MessageContext, _cancellation: System.Threading.CancellationToken) : System.Threading.Tasks.Task =
        // The actual message body
        let tick = context.Envelope.Message :?> Wolverine.Core.FSharpContracts.Tick

        Wolverine.Runtime.WolverineTracing.ApplyExecutionDiagnosticTags(System.Diagnostics.Activity.Current, context.Envelope)
        let tickMiddleware = Wolverine.Core.FSharpContracts.TickMiddleware()
        tickMiddleware.Before()
        try
            if not (isNull System.Diagnostics.Activity.Current) then
                System.Diagnostics.Activity.Current.SetTag("message.handler", "Wolverine.Core.FSharpContracts.TickHandler") |> ignore
                System.Diagnostics.Activity.Current.SetTag("handler.type", "Wolverine.Core.FSharpContracts.TickHandler") |> ignore
            let tickHandler = Wolverine.Core.FSharpContracts.TickHandler()
            
            // The actual message execution
            tickHandler.Handle(tick)

            this.RecordCauseAndEffect(context, context.Runtime.Observer)
        finally
            tickMiddleware.Finally()
        System.Threading.Tasks.Task.CompletedTask

