using System.Runtime.CompilerServices;
using JasperFx.CodeGeneration;
using JasperFx.CodeGeneration.Frames;
using Wolverine.Core.FSharpContracts;
using Wolverine.Runtime.Handlers;

namespace Wolverine.Core.FSharpTests;

/// <summary>
///     Builds the "milestone 0" <see cref="GeneratedAssembly" /> for Wolverine's F# code generation
///     (issue GH-2969): a single generated type that implements <see cref="IFoundationProbe" /> and
///     exercises the smallest real Wolverine frame — <see cref="MessageContextFrame" /> — alongside
///     the JasperFx-provided <see cref="CommentFrame" /> and <see cref="ReturnFrame" />.
/// </summary>
/// <remarks>
///     This is the foundation harness: it proves the regenerate → compile pipeline end-to-end with a
///     deterministic, fully-controlled assembly. Phase A replaces this hand-built assembly with a real
///     <c>HandlerGraph</c> rendering (<c>handlerGraph.StartAssembly(rules)</c> +
///     <c>file.AssembleTypes(assembly)</c> + <c>assembly.GenerateFSharpCode()</c>) and richer handlers.
/// </remarks>
public static class FSharpCodegenSample
{
    public const string GeneratedNamespace = "Wolverine.Core.FSharpFixture.Generated";

    public static GeneratedAssembly BuildSampleAssembly()
    {
        var assembly = new GeneratedAssembly(new GenerationRules(GeneratedNamespace));

        var type = assembly.AddType("GeneratedFoundationProbe", typeof(IFoundationProbe));
        var method = type.MethodFor(nameof(IFoundationProbe.Run));

        // A leading comment (CommentFrame emits identical F# / C#).
        method.Frames.Add(new CommentFrame("Generated by Wolverine F# code generation (GH-2969 foundation probe)"));

        // The headline Wolverine frame under test: `let messageContext = MessageContext(runtime)`.
        method.Frames.Add(new MessageContextFrame());

        // A trailing unit expression so the F# member body is complete: `()`.
        method.Frames.Add(new ReturnFrame());

        return assembly;
    }

    /// <summary>Builds the sample and renders it as F# source.</summary>
    public static string GenerateCode()
    {
        return BuildSampleAssembly().GenerateFSharpCode();
    }

    /// <summary>
    ///     The checked-in fixture's <c>Generated.fs</c>, located relative to this source file so it
    ///     resolves regardless of the test runner's working directory or bin layout.
    /// </summary>
    public static string DefaultGeneratedFilePath([CallerFilePath] string thisFile = "")
    {
        var testProjectDir = Path.GetDirectoryName(thisFile)!;
        var srcTestingDir = Path.GetDirectoryName(testProjectDir)!;
        return Path.Combine(srcTestingDir, "Wolverine.Core.FSharpFixture", "Generated.fs");
    }

    public static string FixtureProjectPath([CallerFilePath] string thisFile = "")
    {
        var testProjectDir = Path.GetDirectoryName(thisFile)!;
        var srcTestingDir = Path.GetDirectoryName(testProjectDir)!;
        return Path.Combine(srcTestingDir, "Wolverine.Core.FSharpFixture", "Wolverine.Core.FSharpFixture.fsproj");
    }
}
