<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>Azure Blob Storage document persistence, saga storage, and claim check storage for Wolverine applications</Description>
        <PackageId>WolverineFx.AzureBlobStorage</PackageId>
        <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
        <GenerateAssemblyCopyrightAttribute>false</GenerateAssemblyCopyrightAttribute>
        <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
        <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
        <GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Wolverine\Wolverine.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Azure.Storage.Blobs" />
    </ItemGroup>

</Project>
