// <auto-generated/>

namespace Internal.Generated.WolverineHandlers

open Microsoft.AspNetCore.Http
open Microsoft.AspNetCore.Routing
open System
open System.Linq
open System.Threading.Tasks
open Wolverine.Http

type GET_fsharp_hello(wolverineHttpOptions: Wolverine.Http.WolverineHttpOptions) =
    inherit Wolverine.Http.HttpHandler(wolverineHttpOptions)
    let _wolverineHttpOptions = wolverineHttpOptions

    override this.Handle(httpContext: Microsoft.AspNetCore.Http.HttpContext) : System.Threading.Tasks.Task =
        task {
            let thingEndpoints = Wolverine.Http.FSharpContracts.ThingEndpoints()
            
            // The actual HTTP request handler execution
            let result_of_Hello = thingEndpoints.Hello()

            do! Wolverine.Http.HttpHandler.WriteString(httpContext, result_of_Hello)
        }

type POST_fsharp_things(wolverineHttpOptions: Wolverine.Http.WolverineHttpOptions) =
    inherit Wolverine.Http.HttpHandler(wolverineHttpOptions)
    let _wolverineHttpOptions = wolverineHttpOptions

    override this.Handle(httpContext: Microsoft.AspNetCore.Http.HttpContext) : System.Threading.Tasks.Task =
        task {
            // Reading the request body via JSON deserialization
            let! (command, jsonContinue) = this.ReadJsonAsync<Wolverine.Http.FSharpContracts.CreateThing>(httpContext)
            if jsonContinue = Wolverine.HandlerContinuation.Stop then
                ()
            else
                let thingEndpoints = Wolverine.Http.FSharpContracts.ThingEndpoints()
                
                // The actual HTTP request handler execution
                let thingCreated_response = thingEndpoints.Create(command)

                // Writing the response body to JSON because this was the first 'return variable' in the method signature
                do! this.WriteJsonAsync(httpContext, thingCreated_response)
        }

