// <auto-generated/>

namespace Internal.Generated.WolverineHandlers

open Microsoft.AspNetCore.Http
open Microsoft.AspNetCore.Routing
open System
open System.Linq
open System.Threading.Tasks
open Wolverine.Http
open Wolverine.Runtime

type GET_fsharp_hello(wolverineHttpOptions: Wolverine.Http.WolverineHttpOptions) =
    inherit Wolverine.Http.HttpHandler(wolverineHttpOptions)
    let _wolverineHttpOptions = wolverineHttpOptions

    override this.Handle(httpContext: Microsoft.AspNetCore.Http.HttpContext) : System.Threading.Tasks.Task =
        task {

            // Tenant Id detection
            // 1. Tenant Id is request header 'x-tenant-id'
            let! tenantId = this.TryDetectTenantId(httpContext)
            if not (isNull System.Diagnostics.Activity.Current) then System.Diagnostics.Activity.Current.SetTag("handler.type", "Wolverine.Http.FSharpContracts.ThingEndpoints") |> ignore
            let thingEndpoints = Wolverine.Http.FSharpContracts.ThingEndpoints()
            
            // The actual HTTP request handler execution
            let result_of_Hello = thingEndpoints.Hello()

            do! Wolverine.Http.HttpHandler.WriteString(httpContext, result_of_Hello)
        }

type POST_fsharp_things(wolverineHttpOptions: Wolverine.Http.WolverineHttpOptions) =
    inherit Wolverine.Http.HttpHandler(wolverineHttpOptions)
    let _wolverineHttpOptions = wolverineHttpOptions

    override this.Handle(httpContext: Microsoft.AspNetCore.Http.HttpContext) : System.Threading.Tasks.Task =
        task {

            // Tenant Id detection
            // 1. Tenant Id is request header 'x-tenant-id'
            let! tenantId = this.TryDetectTenantId(httpContext)
            if not (isNull System.Diagnostics.Activity.Current) then System.Diagnostics.Activity.Current.SetTag("handler.type", "Wolverine.Http.FSharpContracts.ThingEndpoints") |> ignore
            // Reading the request body via JSON deserialization
            let! struct (command, jsonContinue) = this.ReadJsonAsync<Wolverine.Http.FSharpContracts.CreateThing>(httpContext)
            if jsonContinue = Wolverine.HandlerContinuation.Stop then
                ()
            else
                let thingEndpoints = Wolverine.Http.FSharpContracts.ThingEndpoints()
                
                // The actual HTTP request handler execution
                let thingCreated_response = thingEndpoints.Create(command)

                // Writing the response body to JSON because this was the first 'return variable' in the method signature
                do! this.WriteJsonAsync(httpContext, thingCreated_response)
        }

type GET_fsharp_things_id(wolverineHttpOptions: Wolverine.Http.WolverineHttpOptions) =
    inherit Wolverine.Http.HttpHandler(wolverineHttpOptions)
    let _wolverineHttpOptions = wolverineHttpOptions

    override this.Handle(httpContext: Microsoft.AspNetCore.Http.HttpContext) : System.Threading.Tasks.Task =
        task {

            // Tenant Id detection
            // 1. Tenant Id is request header 'x-tenant-id'
            let! tenantId = this.TryDetectTenantId(httpContext)
            if not (isNull System.Diagnostics.Activity.Current) then System.Diagnostics.Activity.Current.SetTag("handler.type", "Wolverine.Http.FSharpContracts.ThingEndpoints") |> ignore
            let id = (httpContext.GetRouteValue("id") :?> string)
            if isNull id then
                httpContext.Response.StatusCode <- 404
                ()
            else
                let thingEndpoints = Wolverine.Http.FSharpContracts.ThingEndpoints()
                
                // The actual HTTP request handler execution
                let result_of_GetById = thingEndpoints.GetById(id)

                do! Wolverine.Http.HttpHandler.WriteString(httpContext, result_of_GetById)
        }

type GET_fsharp_search(wolverineHttpOptions: Wolverine.Http.WolverineHttpOptions) =
    inherit Wolverine.Http.HttpHandler(wolverineHttpOptions)
    let _wolverineHttpOptions = wolverineHttpOptions

    override this.Handle(httpContext: Microsoft.AspNetCore.Http.HttpContext) : System.Threading.Tasks.Task =
        task {

            // Tenant Id detection
            // 1. Tenant Id is request header 'x-tenant-id'
            let! tenantId = this.TryDetectTenantId(httpContext)
            if not (isNull System.Diagnostics.Activity.Current) then System.Diagnostics.Activity.Current.SetTag("handler.type", "Wolverine.Http.FSharpContracts.ThingEndpoints") |> ignore
            let q = httpContext.Request.Query.["q"].ToString()
            let thingEndpoints = Wolverine.Http.FSharpContracts.ThingEndpoints()
            
            // The actual HTTP request handler execution
            let result_of_Search = thingEndpoints.Search(q)

            do! Wolverine.Http.HttpHandler.WriteString(httpContext, result_of_Search)
        }

type GET_fsharp_things_id_items_count(wolverineHttpOptions: Wolverine.Http.WolverineHttpOptions) =
    inherit Wolverine.Http.HttpHandler(wolverineHttpOptions)
    let _wolverineHttpOptions = wolverineHttpOptions

    override this.Handle(httpContext: Microsoft.AspNetCore.Http.HttpContext) : System.Threading.Tasks.Task =
        task {

            // Tenant Id detection
            // 1. Tenant Id is request header 'x-tenant-id'
            let! tenantId = this.TryDetectTenantId(httpContext)
            if not (isNull System.Diagnostics.Activity.Current) then System.Diagnostics.Activity.Current.SetTag("handler.type", "Wolverine.Http.FSharpContracts.ThingEndpoints") |> ignore
            let id = (httpContext.GetRouteValue("id") :?> string)
            if isNull id then
                httpContext.Response.StatusCode <- 404
                ()
            else
                let count_rawValue = (httpContext.GetRouteValue("count") :?> string)
                if isNull count_rawValue then
                    httpContext.Response.StatusCode <- 404
                    ()
                else
                    match System.Int32.TryParse(count_rawValue, System.Globalization.CultureInfo.InvariantCulture) with
                        | true, count ->
                            let thingEndpoints = Wolverine.Http.FSharpContracts.ThingEndpoints()
                            
                            // The actual HTTP request handler execution
                            let result_of_GetItems = thingEndpoints.GetItems(id, count)

                            do! Wolverine.Http.HttpHandler.WriteString(httpContext, result_of_GetItems)
                        | _ ->
                            httpContext.Response.StatusCode <- 404
                            ()
        }

type GET_fsharp_paged(wolverineHttpOptions: Wolverine.Http.WolverineHttpOptions) =
    inherit Wolverine.Http.HttpHandler(wolverineHttpOptions)
    let _wolverineHttpOptions = wolverineHttpOptions

    override this.Handle(httpContext: Microsoft.AspNetCore.Http.HttpContext) : System.Threading.Tasks.Task =
        task {

            // Tenant Id detection
            // 1. Tenant Id is request header 'x-tenant-id'
            let! tenantId = this.TryDetectTenantId(httpContext)
            if not (isNull System.Diagnostics.Activity.Current) then System.Diagnostics.Activity.Current.SetTag("handler.type", "Wolverine.Http.FSharpContracts.ThingEndpoints") |> ignore
            let page_rawValue = httpContext.Request.Query.["page"].ToString()
            let page = match System.Int32.TryParse(page_rawValue, System.Globalization.CultureInfo.InvariantCulture) with | true, v -> v | _ -> Unchecked.defaultof<int>
            let thingEndpoints = Wolverine.Http.FSharpContracts.ThingEndpoints()
            
            // The actual HTTP request handler execution
            let result_of_Paged = thingEndpoints.Paged(page)

            do! Wolverine.Http.HttpHandler.WriteString(httpContext, result_of_Paged)
        }

type GET_fsharp_result_id(wolverineHttpOptions: Wolverine.Http.WolverineHttpOptions) =
    inherit Wolverine.Http.HttpHandler(wolverineHttpOptions)
    let _wolverineHttpOptions = wolverineHttpOptions

    override this.Handle(httpContext: Microsoft.AspNetCore.Http.HttpContext) : System.Threading.Tasks.Task =
        task {

            // Tenant Id detection
            // 1. Tenant Id is request header 'x-tenant-id'
            let! tenantId = this.TryDetectTenantId(httpContext)
            if not (isNull System.Diagnostics.Activity.Current) then System.Diagnostics.Activity.Current.SetTag("handler.type", "Wolverine.Http.FSharpContracts.ThingEndpoints") |> ignore
            let id = (httpContext.GetRouteValue("id") :?> string)
            if isNull id then
                httpContext.Response.StatusCode <- 404
                ()
            else
                let thingEndpoints = Wolverine.Http.FSharpContracts.ThingEndpoints()
                
                // The actual HTTP request handler execution
                let result = thingEndpoints.GetResult(id)

                do! result.ExecuteAsync(httpContext)
        }

type DELETE_fsharp_things_id(wolverineHttpOptions: Wolverine.Http.WolverineHttpOptions) =
    inherit Wolverine.Http.HttpHandler(wolverineHttpOptions)
    let _wolverineHttpOptions = wolverineHttpOptions

    override this.Handle(httpContext: Microsoft.AspNetCore.Http.HttpContext) : System.Threading.Tasks.Task =
        task {

            // Tenant Id detection
            // 1. Tenant Id is request header 'x-tenant-id'
            let! tenantId = this.TryDetectTenantId(httpContext)
            if not (isNull System.Diagnostics.Activity.Current) then System.Diagnostics.Activity.Current.SetTag("handler.type", "Wolverine.Http.FSharpContracts.ThingEndpoints") |> ignore
            let id = (httpContext.GetRouteValue("id") :?> string)
            if isNull id then
                httpContext.Response.StatusCode <- 404
                ()
            else
                let thingEndpoints = Wolverine.Http.FSharpContracts.ThingEndpoints()
                
                // The actual HTTP request handler execution
                thingEndpoints.Delete(id)

                // Wolverine automatically sets the status code to 204 for empty responses
                if not httpContext.Response.HasStarted && httpContext.Response.StatusCode = 200 then
                    httpContext.Response.StatusCode <- 204
        }

type POST_fsharp_publish(wolverineHttpOptions: Wolverine.Http.WolverineHttpOptions, wolverineRuntime: Wolverine.Runtime.IWolverineRuntime) =
    inherit Wolverine.Http.HttpHandler(wolverineHttpOptions)
    let _wolverineHttpOptions = wolverineHttpOptions
    let _wolverineRuntime = wolverineRuntime

    override this.Handle(httpContext: Microsoft.AspNetCore.Http.HttpContext) : System.Threading.Tasks.Task =
        task {

            // Tenant Id detection
            // 1. Tenant Id is request header 'x-tenant-id'
            let! tenantId = this.TryDetectTenantId(httpContext)
            let messageContext = Wolverine.Runtime.MessageContext(_wolverineRuntime)
            messageContext.TenantId <- tenantId
            if not (isNull System.Diagnostics.Activity.Current) then System.Diagnostics.Activity.Current.SetTag("handler.type", "Wolverine.Http.FSharpContracts.ThingEndpoints") |> ignore
            // Reading the request body via JSON deserialization
            let! struct (command, jsonContinue) = this.ReadJsonAsync<Wolverine.Http.FSharpContracts.CreateThing>(httpContext)
            if jsonContinue = Wolverine.HandlerContinuation.Stop then
                ()
            else
                let thingEndpoints = Wolverine.Http.FSharpContracts.ThingEndpoints()
                
                // The actual HTTP request handler execution
                let thingCreated_response = thingEndpoints.Publish(command, messageContext)

                // Writing the response body to JSON because this was the first 'return variable' in the method signature
                do! this.WriteJsonAsync(httpContext, thingCreated_response)
                
                // Have to flush outgoing messages just in case Marten did nothing because of https://github.com/JasperFx/wolverine/issues/536
                do! messageContext.FlushOutgoingMessagesAsync()

        }

type GET_fsharp_filter(wolverineHttpOptions: Wolverine.Http.WolverineHttpOptions) =
    inherit Wolverine.Http.HttpHandler(wolverineHttpOptions)
    let _wolverineHttpOptions = wolverineHttpOptions

    override this.Handle(httpContext: Microsoft.AspNetCore.Http.HttpContext) : System.Threading.Tasks.Task =
        task {
            let MaxResults_rawValue = httpContext.Request.Query.["MaxResults"].ToString()
            let MaxResults = match System.Int32.TryParse(MaxResults_rawValue, System.Globalization.CultureInfo.InvariantCulture) with | true, v -> v | _ -> Unchecked.defaultof<int>
            let Name = httpContext.Request.Query.["Name"].ToString()

            // Tenant Id detection
            // 1. Tenant Id is request header 'x-tenant-id'
            let! tenantId = this.TryDetectTenantId(httpContext)
            if not (isNull System.Diagnostics.Activity.Current) then System.Diagnostics.Activity.Current.SetTag("handler.type", "Wolverine.Http.FSharpContracts.ThingEndpoints") |> ignore
            // Binding QueryString values to the argument marked with [FromQuery]
            let thingFilter : Wolverine.Http.FSharpContracts.ThingFilter = Wolverine.Http.FSharpContracts.ThingFilter(Name, MaxResults)
            let thingEndpoints = Wolverine.Http.FSharpContracts.ThingEndpoints()
            
            // The actual HTTP request handler execution
            let thingCreated_response = thingEndpoints.Filter(thingFilter)

            // Writing the response body to JSON because this was the first 'return variable' in the method signature
            do! this.WriteJsonAsync(httpContext, thingCreated_response)
        }

type GET_fsharp_authed(wolverineHttpOptions: Wolverine.Http.WolverineHttpOptions) =
    inherit Wolverine.Http.HttpHandler(wolverineHttpOptions)
    let _wolverineHttpOptions = wolverineHttpOptions

    override this.Handle(httpContext: Microsoft.AspNetCore.Http.HttpContext) : System.Threading.Tasks.Task =
        task {

            // Tenant Id detection
            // 1. Tenant Id is request header 'x-tenant-id'
            let! tenantId = this.TryDetectTenantId(httpContext)
            if not (isNull System.Diagnostics.Activity.Current) then System.Diagnostics.Activity.Current.SetTag("handler.type", "Wolverine.Http.FSharpContracts.AuthedEndpoints") |> ignore
            let result1 = Wolverine.Http.FSharpContracts.AuthHelpers.CheckAuth()
            // Evaluate whether or not the execution should be stopped based on the IResult value
            if not (isNull (result1 :> obj)) && not (result1 :? Wolverine.Http.WolverineContinue) then
                do! result1.ExecuteAsync(httpContext)
                return ()

            let authedEndpoints = Wolverine.Http.FSharpContracts.AuthedEndpoints()
            
            // The actual HTTP request handler execution
            let result_of_Get = authedEndpoints.Get()

            do! Wolverine.Http.HttpHandler.WriteString(httpContext, result_of_Get)
        }

type GeneratedHttpEndpointRegistry() =
    inherit Wolverine.Http.HttpEndpointRegistry()
    override this.EndpointTypes() : System.Type[] =
        [| "Wolverine.Http.FSharpContracts.AuthedEndpoints, Wolverine.Http.FSharpContracts, Version=6.22.0.0, Culture=neutral, PublicKeyToken=null"; "Wolverine.Http.FSharpContracts.ThingEndpoints, Wolverine.Http.FSharpContracts, Version=6.22.0.0, Culture=neutral, PublicKeyToken=null" |] |> Array.choose (fun n -> System.Type.GetType(n) |> Option.ofObj)

