// <auto-generated/>

namespace Internal.Generated.WolverineHandlers

open Microsoft.AspNetCore.Http
open Microsoft.AspNetCore.Routing
open System
open System.Linq
open System.Threading.Tasks
open Wolverine.Http

type GET_fsharp_hello(wolverineHttpOptions: Wolverine.Http.WolverineHttpOptions) =
    inherit Wolverine.Http.HttpHandler(wolverineHttpOptions)
    let _wolverineHttpOptions = wolverineHttpOptions

    override _.Handle(httpContext: Microsoft.AspNetCore.Http.HttpContext) : System.Threading.Tasks.Task =
        task {
            let thingEndpoints = Wolverine.Http.FSharpContracts.ThingEndpoints()
            
            // The actual HTTP request handler execution
            let result_of_Hello = thingEndpoints.Hello()

            do! Wolverine.Http.HttpHandler.WriteString(httpContext, result_of_Hello)
        }

