namespace Wolverine.Attributes;

/// <summary>
/// Applied by the Wolverine source generator to mark an assembly as containing
/// a compile-time type manifest. During startup, Wolverine checks for this
/// attribute on the application assembly. If found, it instantiates the
/// specified IWolverineTypeLoader to bypass runtime assembly scanning.
///
/// This attribute is not intended to be applied manually. It is emitted
/// by the Wolverine.SourceGeneration package.
/// </summary>
[AttributeUsage(AttributeTargets.Assembly, AllowMultiple = false)]
public sealed class WolverineTypeManifestAttribute : Attribute
{
    /// <summary>
    /// The Type that implements IWolverineTypeLoader, generated by the source generator.
    /// </summary>
    public Type LoaderType { get; }

    public WolverineTypeManifestAttribute(Type loaderType)
    {
        LoaderType = loaderType ?? throw new ArgumentNullException(nameof(loaderType));
    }
}
