// <auto-generated />
using System.Collections.Generic;

namespace Wolverine.SourceGeneration
{
    /// <summary>
    /// Metadata about a discovered handler type collected during syntax/semantic analysis.
    /// </summary>
    internal sealed class HandlerTypeInfo
    {
        public HandlerTypeInfo(string fullName, string namespaceName, string className)
        {
            FullName = fullName;
            NamespaceName = namespaceName;
            ClassName = className;
        }

        public string FullName { get; }
        public string NamespaceName { get; }
        public string ClassName { get; }

        /// <summary>
        /// Message types discovered from handler method first parameters.
        /// Each entry is (FullTypeName, Alias) where alias is the simple type name.
        /// </summary>
        public List<(string FullTypeName, string Alias)> MessageTypes { get; } = new List<(string, string)>();
    }
}
