// <auto-generated/>

namespace Internal.Generated.WolverineHandlers

open System
open System.Threading
open System.Threading.Tasks
open Wolverine.Marten.Publishing
open Wolverine.Runtime
open Wolverine.Runtime.Handlers

type CreateProductCommandHandler1629670092(outboxedSessionFactory: Wolverine.Marten.Publishing.OutboxedSessionFactory) =
    inherit Wolverine.Runtime.Handlers.MessageHandler()
    let _outboxedSessionFactory = outboxedSessionFactory

    override this.HandleAsync(context: Wolverine.Runtime.MessageContext, cancellation: System.Threading.CancellationToken) : System.Threading.Tasks.Task =
        task {
            // Building the Marten session
            use documentSession = _outboxedSessionFactory.OpenSession(context)
            // The actual message body
            let createProductCommand = context.Envelope.Message :?> WolverineMartenFSharpSample.CreateProductCommand

            if not (isNull System.Diagnostics.Activity.Current) then
                System.Diagnostics.Activity.Current.SetTag("message.handler", "WolverineMartenFSharpSample.CreateProductHandler") |> ignore
                System.Diagnostics.Activity.Current.SetTag("handler.type", "WolverineMartenFSharpSample.CreateProductHandler") |> ignore
            
            // The actual message execution
            let outgoing1 = WolverineMartenFSharpSample.CreateProductHandler.Handle(createProductCommand, documentSession)

            
            // Outgoing, cascaded message
            do! context.EnqueueCascadingAsync(outgoing1)

            
            // Save all pending changes to this Marten session
            do! documentSession.SaveChangesAsync(cancellation)

            
            // Have to flush outgoing messages just in case Marten did nothing because of https://github.com/JasperFx/wolverine/issues/536
            do! context.FlushOutgoingMessagesAsync()

        }

