// <auto-generated/>

namespace Internal.Generated.WolverineHandlers

open Microsoft.Azure.Cosmos
open System
open System.Threading
open System.Threading.Tasks
open Wolverine.FluentValidation
open Wolverine.Runtime
open Wolverine.Runtime.Handlers

type CreateThingHandler2004325667(container: Microsoft.Azure.Cosmos.Container, failureActionOfCreateThing: Wolverine.FluentValidation.IFailureAction<WolverineCosmosFSharpSample.CreateThing>) =
    inherit Wolverine.Runtime.Handlers.MessageHandler()
    let _container = container
    let _failureActionOfCreateThing = failureActionOfCreateThing

    override this.HandleAsync(context: Wolverine.Runtime.MessageContext, cancellation: System.Threading.CancellationToken) : System.Threading.Tasks.Task =
        task {
            let createThingValidator = WolverineCosmosFSharpSample.CreateThingValidator()
            // The actual message body
            let createThing = context.Envelope.Message :?> WolverineCosmosFSharpSample.CreateThing

            if not (isNull System.Diagnostics.Activity.Current) then
                System.Diagnostics.Activity.Current.SetTag("message.handler", "WolverineCosmosFSharpSample.CreateThingHandler") |> ignore
                System.Diagnostics.Activity.Current.SetTag("handler.type", "WolverineCosmosFSharpSample.CreateThingHandler") |> ignore
            do! Wolverine.FluentValidation.Internals.FluentValidationExecutor.ExecuteOne<WolverineCosmosFSharpSample.CreateThing>(createThingValidator, _failureActionOfCreateThing, createThing)

            // Enlist in CosmosDB outbox transaction
            context.EnlistInOutbox(Wolverine.CosmosDb.Internals.CosmosDbEnvelopeTransaction(_container, context))
            
            // The actual message execution
            let outgoing1 = WolverineCosmosFSharpSample.CreateThingHandler.Handle(createThing)

            if not (isNull outgoing1) then
                
                // Placed by Wolverine's ISideEffect policy
                do! outgoing1.Execute(_container)

            
            // Have to flush outgoing messages just in case Marten did nothing because of https://github.com/JasperFx/wolverine/issues/536
            do! context.FlushOutgoingMessagesAsync()

        }

