using System.Diagnostics;
using System.Reflection;
using Grpc.Core;
using JasperFx;
using JasperFx.CodeGeneration;
using JasperFx.CodeGeneration.Frames;
using JasperFx.CodeGeneration.Model;
using JasperFx.Core.Reflection;
using Wolverine.Attributes;
using Wolverine.Configuration;
using Wolverine.Middleware;
using Wolverine.Persistence;

namespace Wolverine.Grpc;

/// <summary>
///     Represents a proto-first gRPC service that Wolverine will wrap with a generated
///     concrete subclass. Each method on the proto-generated <c>*Base</c> class that
///     matches the unary-RPC signature <c>Task&lt;TResponse&gt;(TRequest, ServerCallContext)</c>
///     is overridden to forward to <see cref="IMessageBus.InvokeAsync{T}"/>.
/// </summary>
public class GrpcServiceChain : Chain<GrpcServiceChain, ModifyGrpcServiceChainAttribute>, ICodeFile
{
    private readonly GrpcGraph _parent;
    private GeneratedType? _generatedType;
    private Type? _generatedRuntimeType;

    /// <summary>
    ///     The user-defined stub type carrying <see cref="WolverineGrpcServiceAttribute"/>.
    ///     This stub must derive from a proto-generated service base class.
    /// </summary>
    public Type StubType { get; }

    /// <summary>
    ///     The proto-generated base class (e.g., <c>Greeter.GreeterBase</c>) detected via the
    ///     <see cref="BindServiceMethodAttribute"/> marker that <c>Grpc.Tools</c> stamps on
    ///     generated service bases.
    /// </summary>
    public Type ProtoServiceBase { get; }

    /// <summary>
    ///     The unary RPC methods discovered on <see cref="ProtoServiceBase"/> that will be
    ///     overridden in the generated wrapper.
    /// </summary>
    public IReadOnlyList<MethodInfo> UnaryMethods { get; }

    /// <summary>
    ///     The C# identifier used for the generated wrapper type. Initialised from
    ///     <see cref="ProtoServiceName"/> as <c>{ProtoServiceName}GrpcHandler</c>; rewritten by
    ///     <see cref="GrpcGraph.DisambiguateCollidingTypeNames"/> if two discovered chains end up
    ///     with the same default name (e.g., two assemblies shipping a <c>Greeter</c> proto service).
    /// </summary>
    public string TypeName { get; private set; }

    public GrpcServiceChain(Type stubType, GrpcGraph parent)
    {
        _parent = parent ?? throw new ArgumentNullException(nameof(parent));
        StubType = stubType ?? throw new ArgumentNullException(nameof(stubType));

        ProtoServiceBase = FindProtoServiceBase(stubType)
            ?? throw new InvalidOperationException(
                $"Type {stubType.FullNameInCode()} is marked as a proto-first Wolverine gRPC service, but no proto-generated base class was found in its inheritance chain. "
                + "The stub must derive from a class carrying [BindServiceMethod] (generated by Grpc.Tools from a .proto file).");

        SupportedMethods = DiscoverSupportedMethods(ProtoServiceBase).ToArray();
        AssertNoUnsupportedStreamingKinds(stubType, SupportedMethods);

        UnaryMethods = SupportedMethods
            .Where(m => m.Kind == GrpcMethodKind.Unary)
            .Select(m => m.Method)
            .ToArray();
        ServerStreamingMethods = SupportedMethods
            .Where(m => m.Kind == GrpcMethodKind.ServerStreaming)
            .Select(m => m.Method)
            .ToArray();
        BidirectionalStreamingMethods = SupportedMethods
            .Where(m => m.Kind == GrpcMethodKind.BidirectionalStreaming)
            .Select(m => m.Method)
            .ToArray();

        ProtoServiceName = ResolveProtoServiceName(ProtoServiceBase);
        TypeName = ProtoServiceName + "GrpcHandler";
        Description = $"Generated proto-first gRPC service wrapper for {stubType.FullNameInCode()} (proto base: {ProtoServiceBase.FullNameInCode()})";
    }

    /// <summary>
    ///     All supported RPC methods Wolverine will override on the generated wrapper.
    /// </summary>
    public IReadOnlyList<GrpcRpcMethod> SupportedMethods { get; }

    /// <summary>
    ///     Server-streaming RPC methods (<c>Task Name(TRequest, IServerStreamWriter&lt;TResponse&gt;, ServerCallContext)</c>)
    ///     that forward each streamed item to <see cref="IMessageBus.StreamAsync{T}"/>.
    /// </summary>
    public IReadOnlyList<MethodInfo> ServerStreamingMethods { get; }

    /// <summary>
    ///     Bidirectional-streaming RPC methods
    ///     (<c>Task Name(IAsyncStreamReader&lt;TRequest&gt;, IServerStreamWriter&lt;TResponse&gt;, ServerCallContext)</c>)
    ///     that loop each inbound item through <see cref="IMessageBus.StreamAsync{T}"/> and
    ///     forward each yielded response to the stream writer.
    /// </summary>
    public IReadOnlyList<MethodInfo> BidirectionalStreamingMethods { get; }

    /// <summary>
    ///     The proto service name (e.g., <c>Greeter</c>) — used to derive the generated type's name
    ///     as <c>{ProtoServiceName}GrpcHandler</c>. This is the stable identity of the service in
    ///     the wire protocol and tooling, not the user's stub class name.
    /// </summary>
    public string ProtoServiceName { get; }

    public override string Description { get; }

    public override MiddlewareScoping Scoping => MiddlewareScoping.Grpc;

    private MethodInfo[]? _discoveredBefores;
    private MethodInfo[]? _discoveredAfters;

    /// <summary>
    ///     Methods declared on <see cref="StubType"/> (or its proto base) that qualify as
    ///     <c>[WolverineBefore]</c> middleware for this chain — i.e., named per
    ///     <see cref="MiddlewarePolicy.BeforeMethodNames"/> or carrying the attribute, and whose
    ///     scope (<see cref="MiddlewareScoping"/>) admits <see cref="MiddlewareScoping.Grpc"/>.
    ///     Sorted ordinally by method name so Phase-1 generated source is byte-stable across
    ///     runs (reflection order is not guaranteed). Computed lazily; the returned reference
    ///     is stable across reads.
    /// </summary>
    public IReadOnlyList<MethodInfo> DiscoveredBefores
        => _discoveredBefores ??= MiddlewarePolicy
            .FilterMethods<WolverineBeforeAttribute>(this, StubType.GetMethods(), MiddlewarePolicy.BeforeMethodNames)
            .OrderBy(m => m.Name, StringComparer.Ordinal)
            .ToArray();

    /// <summary>
    ///     Methods declared on <see cref="StubType"/> (or its proto base) that qualify as
    ///     <c>[WolverineAfter]</c> postprocessors for this chain. Same scope, name-convention,
    ///     and ordinal-sort rules as <see cref="DiscoveredBefores"/>.
    /// </summary>
    public IReadOnlyList<MethodInfo> DiscoveredAfters
        => _discoveredAfters ??= MiddlewarePolicy
            .FilterMethods<WolverineAfterAttribute>(this, StubType.GetMethods(), MiddlewarePolicy.AfterMethodNames)
            .OrderBy(m => m.Name, StringComparer.Ordinal)
            .ToArray();

    public override IdempotencyStyle Idempotency { get; set; } = IdempotencyStyle.None;

    /// <summary>
    ///     Applies a disambiguated <see cref="TypeName"/> on a chain whose default name collides
    ///     with another discovered chain. Called exclusively from
    ///     <see cref="GrpcGraph.DisambiguateCollidingTypeNames"/>.
    /// </summary>
    internal void ApplyDisambiguatedTypeName(string disambiguatedName)
    {
        TypeName = disambiguatedName;
    }

    /// <summary>
    ///     The runtime <see cref="Type"/> of the generated wrapper once compiled. Null before compilation.
    /// </summary>
    public Type? GeneratedType => _generatedRuntimeType;

    internal string? SourceCode => _generatedType?.SourceCode;

    public override void ApplyParameterMatching(MethodCall call)
    {
        // no-op: proto-first chains don't route through MethodCall parameter matching
    }

    public override bool TryInferMessageIdentity(out PropertyInfo? property)
    {
        property = null;
        return false;
    }

    public override bool HasAttribute<T>()
    {
        return StubType.HasAttribute<T>();
    }

    public override Type? InputType() => null;

    public override bool ShouldFlushOutgoingMessages() => false;

    public override bool RequiresOutbox() => false;

    public override MethodCall[] HandlerCalls() => [];

    public override bool TryFindVariable(string valueName, ValueSource source, Type valueType, out Variable variable)
    {
        variable = default!;
        return false;
    }

    public override Frame[] AddStopConditionIfNull(Variable variable) => [];

    public override void UseForResponse(MethodCall methodCall)
    {
        // no-op: proto-first chains don't synthesize response variables via MethodCall.
    }

    string ICodeFile.FileName => TypeName;

    void ICodeFile.AssembleTypes(GeneratedAssembly assembly)
    {
        if (_generatedType != null) return;

        assembly.ReferenceAssembly(StubType.Assembly);
        assembly.ReferenceAssembly(ProtoServiceBase.Assembly);
        assembly.ReferenceAssembly(typeof(IMessageBus).Assembly);
        assembly.ReferenceAssembly(typeof(ServerCallContext).Assembly);

        _generatedType = assembly.AddType(TypeName, StubType);

        var busField = new InjectedField(typeof(IMessageBus), "bus");
        _generatedType.AllInjectedFields.Add(busField);

        var befores = DiscoveredBefores;
        var afters = DiscoveredAfters;

        foreach (var rpc in SupportedMethods)
        {
            var generatedMethod = _generatedType.MethodFor(rpc.Method.Name);

            // Before-frames (including Validate short-circuit) require a concrete TRequest
            // in scope when the method begins. Bidi methods start with an IAsyncStreamReader<T>
            // rather than a single T — per-call middleware is not woven for them in this release.
            if (rpc.Kind != GrpcMethodKind.BidirectionalStreaming)
            {
                foreach (var before in befores)
                {
                    var call = new MethodCall(StubType, before);
                    generatedMethod.Frames.Add(call);

                    var statusVar = call.Creates.FirstOrDefault(v => v.VariableType == typeof(Status?));
                    if (statusVar != null)
                        generatedMethod.Frames.Add(new GrpcValidateShortCircuitFrame(statusVar));
                }
            }

            switch (rpc.Kind)
            {
                case GrpcMethodKind.Unary:
                    if (afters.Count > 0)
                        generatedMethod.AsyncMode = AsyncMode.AsyncTask;
                    generatedMethod.Frames.Add(new ForwardUnaryToMessageBusFrame(rpc.Method, busField));
                    break;

                case GrpcMethodKind.ServerStreaming:
                    generatedMethod.AsyncMode = AsyncMode.AsyncTask;
                    generatedMethod.Frames.Add(new ForwardServerStreamToMessageBusFrame(rpc.Method, busField));
                    break;

                case GrpcMethodKind.BidirectionalStreaming:
                    generatedMethod.AsyncMode = AsyncMode.AsyncTask;
                    generatedMethod.Frames.Add(new ForwardBidiStreamToMessageBusFrame(rpc.Method, busField));
                    break;
            }

            if (rpc.Kind != GrpcMethodKind.BidirectionalStreaming)
            {
                foreach (var after in afters)
                    generatedMethod.Frames.Add(new MethodCall(StubType, after));
            }
        }
    }

    Task<bool> ICodeFile.AttachTypes(GenerationRules rules, Assembly assembly, IServiceProvider? services,
        string containingNamespace)
    {
        var found = this.As<ICodeFile>().AttachTypesSynchronously(rules, assembly, services, containingNamespace);
        return Task.FromResult(found);
    }

    bool ICodeFile.AttachTypesSynchronously(GenerationRules rules, Assembly assembly, IServiceProvider? services,
        string containingNamespace)
    {
        Debug.WriteLine(_generatedType?.SourceCode);

        _generatedRuntimeType = assembly.ExportedTypes.FirstOrDefault(x => x.Name == TypeName)
                                ?? assembly.GetTypes().FirstOrDefault(x => x.Name == TypeName);

        return _generatedRuntimeType != null;
    }

    /// <summary>
    ///     Derives the proto service name from the proto-generated base class. Grpc.Tools emits
    ///     the abstract base (<c>{Service}Base</c>) nested inside a non-generic static class named
    ///     after the service (<c>{Service}</c>), so <see cref="Type.DeclaringType"/> is the preferred
    ///     source of truth. If there's no declaring type (unusual layouts), fall back to stripping
    ///     the conventional <c>Base</c> suffix.
    /// </summary>
    public static string ResolveProtoServiceName(Type protoServiceBase)
    {
        if (protoServiceBase.DeclaringType != null)
        {
            return protoServiceBase.DeclaringType.Name;
        }

        var name = protoServiceBase.Name;
        return name.EndsWith("Base", StringComparison.Ordinal)
            ? name[..^"Base".Length]
            : name;
    }

    public static Type? FindProtoServiceBase(Type stubType)
    {
        // Walk the inheritance chain and return the first ancestor carrying [BindServiceMethod].
        // That attribute is emitted by Grpc.Tools onto the abstract {Service}Base class.
        var current = stubType.BaseType;
        while (current != null && current != typeof(object))
        {
            if (current.IsDefined(typeof(BindServiceMethodAttribute), inherit: false))
            {
                return current;
            }

            current = current.BaseType;
        }

        return null;
    }

    /// <summary>
    ///     Legacy helper kept for tests and external consumers — returns only unary RPC methods.
    ///     Prefer <see cref="DiscoverSupportedMethods"/> for the full kind-aware view.
    /// </summary>
    public static IEnumerable<MethodInfo> DiscoverUnaryMethods(Type protoServiceBase)
    {
        return DiscoverSupportedMethods(protoServiceBase)
            .Where(m => m.Kind == GrpcMethodKind.Unary)
            .Select(m => m.Method);
    }

    /// <summary>
    ///     Walks the proto-generated service base, classifying each virtual RPC method by its signature.
    ///     Methods with shapes Wolverine can't yet generate (client-streaming, bidirectional-streaming)
    ///     are still returned — the chain constructor fails fast rather than silently skipping them.
    ///     Results are sorted by method name so generated source is byte-stable across runs, which
    ///     keeps diagnostic diffs and code-gen caches deterministic even when reflection reorders methods.
    /// </summary>
    public static IEnumerable<GrpcRpcMethod> DiscoverSupportedMethods(Type protoServiceBase)
    {
        var results = new List<GrpcRpcMethod>();

        foreach (var method in protoServiceBase.GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly))
        {
            if (!method.IsVirtual || method.IsFinal) continue;

            var kind = ClassifyRpcMethod(method);
            if (kind == null) continue;

            results.Add(new GrpcRpcMethod(method, kind.Value));
        }

        results.Sort(static (a, b) => string.CompareOrdinal(a.Method.Name, b.Method.Name));
        return results;
    }

    /// <summary>
    ///     Shape-check each proto RPC method against the four canonical server signatures Grpc.Tools emits.
    ///     Returns null if the method doesn't match any recognized gRPC server signature (e.g., user-added
    ///     non-RPC virtuals).
    /// </summary>
    private static GrpcMethodKind? ClassifyRpcMethod(MethodInfo method)
    {
        var parameters = method.GetParameters();

        // Unary: Task<TResponse> Name(TRequest, ServerCallContext)
        if (parameters.Length == 2
            && parameters[1].ParameterType == typeof(ServerCallContext)
            && method.ReturnType.IsGenericType
            && method.ReturnType.GetGenericTypeDefinition() == typeof(Task<>)
            && IsConcreteMessageType(parameters[0].ParameterType))
        {
            return GrpcMethodKind.Unary;
        }

        // Server-streaming: Task Name(TRequest, IServerStreamWriter<TResponse>, ServerCallContext)
        if (parameters.Length == 3
            && parameters[2].ParameterType == typeof(ServerCallContext)
            && method.ReturnType == typeof(Task)
            && IsConcreteMessageType(parameters[0].ParameterType)
            && IsGenericOf(parameters[1].ParameterType, typeof(IServerStreamWriter<>)))
        {
            return GrpcMethodKind.ServerStreaming;
        }

        // Client-streaming: Task<TResponse> Name(IAsyncStreamReader<TRequest>, ServerCallContext)
        if (parameters.Length == 2
            && parameters[1].ParameterType == typeof(ServerCallContext)
            && method.ReturnType.IsGenericType
            && method.ReturnType.GetGenericTypeDefinition() == typeof(Task<>)
            && IsGenericOf(parameters[0].ParameterType, typeof(IAsyncStreamReader<>)))
        {
            return GrpcMethodKind.ClientStreaming;
        }

        // Bidirectional: Task Name(IAsyncStreamReader<TRequest>, IServerStreamWriter<TResponse>, ServerCallContext)
        if (parameters.Length == 3
            && parameters[2].ParameterType == typeof(ServerCallContext)
            && method.ReturnType == typeof(Task)
            && IsGenericOf(parameters[0].ParameterType, typeof(IAsyncStreamReader<>))
            && IsGenericOf(parameters[1].ParameterType, typeof(IServerStreamWriter<>)))
        {
            return GrpcMethodKind.BidirectionalStreaming;
        }

        return null;
    }

    private static bool IsConcreteMessageType(Type t) => t.IsClass && !t.IsAbstract;

    private static bool IsGenericOf(Type t, Type openGeneric)
        => t.IsGenericType && t.GetGenericTypeDefinition() == openGeneric;

    private static void AssertNoUnsupportedStreamingKinds(Type stubType, IReadOnlyList<GrpcRpcMethod> methods)
    {
        var unsupported = methods
            .Where(m => m.Kind is GrpcMethodKind.ClientStreaming)
            .ToList();

        if (unsupported.Count == 0) return;

        var detail = unsupported
            .Select(m => $"  - {m.Method.Name} ({m.Kind})")
            .Aggregate((a, b) => a + Environment.NewLine + b);

        throw new NotSupportedException(
            $"Proto-first gRPC stub {stubType.FullNameInCode()} declares RPC method(s) whose shape "
            + "Wolverine cannot yet code-generate. Supported today: unary, server-streaming, and bidirectional-streaming. "
            + "Client-streaming (stream TRequest → TResponse) has no adapter path yet."
            + Environment.NewLine
            + "Unsupported method(s):"
            + Environment.NewLine
            + detail
            + Environment.NewLine
            + "Workaround: move the affected RPC(s) into a separate service whose stub is NOT marked "
            + "[WolverineGrpcService], and implement those methods by hand (calling IMessageBus directly).");
    }
}

/// <summary>
///     Classification of a proto-generated RPC method based on its C# signature.
///     Matches the four canonical shapes that <c>Grpc.Tools</c> emits on the server base class.
/// </summary>
public enum GrpcMethodKind
{
    /// <summary>
    ///     Unary RPC: <c>Task&lt;TResponse&gt; Name(TRequest, ServerCallContext)</c>. Forwards to
    ///     <see cref="IMessageBus.InvokeAsync{T}(object, CancellationToken, TimeSpan?)"/>.
    /// </summary>
    Unary,

    /// <summary>
    ///     Server-streaming RPC: <c>Task Name(TRequest, IServerStreamWriter&lt;TResponse&gt;, ServerCallContext)</c>.
    ///     Forwards to <see cref="IMessageBus.StreamAsync{TResponse}(object, CancellationToken)"/> and pumps each
    ///     yielded item to the stream writer.
    /// </summary>
    ServerStreaming,

    /// <summary>
    ///     Client-streaming RPC: <c>Task&lt;TResponse&gt; Name(IAsyncStreamReader&lt;TRequest&gt;, ServerCallContext)</c>.
    ///     Not yet code-generated by Wolverine — detection fails fast at startup rather than silently skipping.
    /// </summary>
    ClientStreaming,

    /// <summary>
    ///     Bidirectional-streaming RPC: <c>Task Name(IAsyncStreamReader&lt;TRequest&gt;, IServerStreamWriter&lt;TResponse&gt;, ServerCallContext)</c>.
    ///     Each inbound item is forwarded to <see cref="IMessageBus.StreamAsync{T}"/>; every yielded
    ///     response is written to the <see cref="IServerStreamWriter{T}"/>.
    /// </summary>
    BidirectionalStreaming
}

/// <summary>
///     A single proto RPC method paired with the Wolverine-recognized <see cref="GrpcMethodKind"/>.
/// </summary>
/// <param name="Method">Reflection handle to the virtual method on the proto-generated service base.</param>
/// <param name="Kind">The RPC shape Wolverine classified this method as.</param>
public readonly record struct GrpcRpcMethod(MethodInfo Method, GrpcMethodKind Kind);

/// <summary>
///     Emits <c>return _bus.InvokeAsync&lt;TResponse&gt;(request, context.CancellationToken);</c>
///     inside an override of a proto-generated unary RPC method.
/// </summary>
internal sealed class ForwardUnaryToMessageBusFrame : SyncFrame
{
    private readonly MethodInfo _rpc;
    private readonly InjectedField _busField;

    public ForwardUnaryToMessageBusFrame(MethodInfo rpc, InjectedField busField)
    {
        _rpc = rpc;
        _busField = busField;
    }

    public override void GenerateCode(GeneratedMethod method, ISourceWriter writer)
    {
        var parameters = _rpc.GetParameters();
        var requestName = ParameterName(parameters, 0);
        var contextName = ParameterName(parameters, 1);
        var responseType = _rpc.ReturnType.GetGenericArguments()[0];
        var cancellation = $"{contextName}.{nameof(ServerCallContext.CancellationToken)}";
        var busInvoke =
            $"{_busField.Usage}.{nameof(IMessageBus.InvokeAsync)}<{responseType.FullNameInCode()}>({requestName}, {cancellation})";

        if (Next == null)
        {
            writer.Write($"return {busInvoke};");
        }
        else
        {
            // After-frames are present — await so they can run before the return.
            writer.Write($"var result = await {busInvoke};");
            Next.GenerateCode(method, writer);
            writer.Write("return result;");
        }
    }

    // Grpc.Tools always emits parameter names, but reflection over optimized assemblies can return null.
    // A stable fallback keeps the generated source compilable even in those odd cases.
    internal static string ParameterName(ParameterInfo[] parameters, int index)
        => parameters[index].Name ?? $"arg{index}";
}

/// <summary>
///     Emits an <c>await foreach</c> loop bridging <see cref="IMessageBus.StreamAsync{T}"/> to a gRPC
///     server-streaming method's <see cref="IServerStreamWriter{T}"/>. The generated method is marked
///     <see cref="AsyncMode.AsyncTask"/> so the <c>await</c> keyword is legal in the body.
/// </summary>
internal sealed class ForwardServerStreamToMessageBusFrame : AsyncFrame
{
    private readonly MethodInfo _rpc;
    private readonly InjectedField _busField;

    public ForwardServerStreamToMessageBusFrame(MethodInfo rpc, InjectedField busField)
    {
        _rpc = rpc;
        _busField = busField;
    }

    public override void GenerateCode(GeneratedMethod method, ISourceWriter writer)
    {
        var parameters = _rpc.GetParameters();
        var requestName = ForwardUnaryToMessageBusFrame.ParameterName(parameters, 0);
        var streamWriterName = ForwardUnaryToMessageBusFrame.ParameterName(parameters, 1);
        var contextName = ForwardUnaryToMessageBusFrame.ParameterName(parameters, 2);

        // IServerStreamWriter<TResponse> → TResponse
        var responseType = parameters[1].ParameterType.GetGenericArguments()[0];
        var cancellation = $"{contextName}.{nameof(ServerCallContext.CancellationToken)}";

        writer.Write(
            $"BLOCK:await foreach (var item in {_busField.Usage}.{nameof(IMessageBus.StreamAsync)}<{responseType.FullNameInCode()}>({requestName}, {cancellation}))");
        writer.Write($"await {streamWriterName}.WriteAsync(item, {cancellation});");
        writer.FinishBlock();

        Next?.GenerateCode(method, writer);
    }
}

/// <summary>
///     Emits a nested <c>while/await foreach</c> loop that bridges a gRPC bidirectional-streaming
///     RPC to Wolverine's <see cref="IMessageBus.StreamAsync{T}"/>. For each item the client
///     sends, the generated wrapper calls <see cref="IMessageBus.StreamAsync{T}"/> and pumps
///     every yielded response to the <see cref="IServerStreamWriter{T}"/>.
/// </summary>
/// <remarks>
///     Generated code shape:
///     <code>
///         while (await requestStream.MoveNext(context.CancellationToken))
///         {
///             var request = requestStream.Current;
///             await foreach (var item in _bus.StreamAsync&lt;TResponse&gt;(request, context.CancellationToken))
///             {
///                 await responseStream.WriteAsync(item, context.CancellationToken);
///             }
///         }
///     </code>
///     Before-frames (including the Validate short-circuit) are not woven into bidirectional methods:
///     they require a concrete <c>TRequest</c> in scope before the loop begins, which is not
///     available in the bidi signature.
/// </remarks>
internal sealed class ForwardBidiStreamToMessageBusFrame : AsyncFrame
{
    private readonly MethodInfo _rpc;
    private readonly InjectedField _busField;

    public ForwardBidiStreamToMessageBusFrame(MethodInfo rpc, InjectedField busField)
    {
        _rpc = rpc;
        _busField = busField;
    }

    public override void GenerateCode(GeneratedMethod method, ISourceWriter writer)
    {
        var parameters = _rpc.GetParameters();
        var readerName = ForwardUnaryToMessageBusFrame.ParameterName(parameters, 0);
        var writerName = ForwardUnaryToMessageBusFrame.ParameterName(parameters, 1);
        var contextName = ForwardUnaryToMessageBusFrame.ParameterName(parameters, 2);

        var responseType = parameters[1].ParameterType.GetGenericArguments()[0];
        var cancellation = $"{contextName}.{nameof(ServerCallContext.CancellationToken)}";

        writer.Write(
            $"BLOCK:while (await {readerName}.{nameof(IAsyncStreamReader<object>.MoveNext)}({cancellation}))");
        writer.Write($"var request = {readerName}.{nameof(IAsyncStreamReader<object>.Current)};");
        writer.Write(
            $"BLOCK:await foreach (var item in {_busField.Usage}.{nameof(IMessageBus.StreamAsync)}<{responseType.FullNameInCode()}>(request, {cancellation}))");
        writer.Write($"await {writerName}.{nameof(IServerStreamWriter<object>.WriteAsync)}(item, {cancellation});");
        writer.FinishBlock();
        writer.FinishBlock();

        Next?.GenerateCode(method, writer);
    }
}

/// <summary>
///     Emits a <c>Status?</c> null-check that short-circuits RPC execution when a
///     <c>Validate</c> / <c>ValidateAsync</c> method on the proto-first stub returns
///     a non-null <see cref="Status"/>. Placed immediately after the <see cref="MethodCall"/>
///     frame for the validate method in <see cref="GrpcServiceChain.AssembleTypes"/>.
/// </summary>
/// <remarks>
///     Generated code shape:
///     <code>
///         if ({statusVar}.HasValue)
///             throw new Grpc.Core.RpcException({statusVar}.Value);
///     </code>
///     When <see cref="Status.StatusCode"/> is <see cref="StatusCode.OK"/> the throw is
///     skipped and the chain continues to the bus-dispatch frame as normal.
/// </remarks>
internal sealed class GrpcValidateShortCircuitFrame : SyncFrame
{
    private readonly Variable _statusVariable;

    public GrpcValidateShortCircuitFrame(Variable statusVariable)
    {
        _statusVariable = statusVariable;
        uses.Add(statusVariable);
    }

    public override void GenerateCode(GeneratedMethod method, ISourceWriter writer)
    {
        writer.Write($"BLOCK:if ({_statusVariable.Usage}.{nameof(Nullable<Status>.HasValue)})");
        writer.Write(
            $"throw new {typeof(RpcException).FullNameInCode()}({_statusVariable.Usage}.{nameof(Nullable<Status>.Value)});");
        writer.FinishBlock();
        writer.BlankLine();

        Next?.GenerateCode(method, writer);
    }
}
