using System.Diagnostics;
using System.Reflection;
using Grpc.Core;
using JasperFx;
using JasperFx.CodeGeneration;
using JasperFx.CodeGeneration.Frames;
using JasperFx.CodeGeneration.Model;
using JasperFx.Core.Reflection;
using Wolverine.Attributes;
using Wolverine.Configuration;
using Wolverine.Persistence;

namespace Wolverine.Grpc;

/// <summary>
///     Represents a proto-first gRPC service that Wolverine will wrap with a generated
///     concrete subclass. Each method on the proto-generated <c>*Base</c> class that
///     matches the unary-RPC signature <c>Task&lt;TResponse&gt;(TRequest, ServerCallContext)</c>
///     is overridden to forward to <see cref="IMessageBus.InvokeAsync{T}"/>.
/// </summary>
public class GrpcServiceChain : Chain<GrpcServiceChain, ModifyGrpcServiceChainAttribute>, ICodeFile
{
    private readonly GrpcGraph _parent;
    private GeneratedType? _generatedType;
    private Type? _generatedRuntimeType;

    /// <summary>
    ///     The user-defined stub type carrying <see cref="WolverineGrpcServiceAttribute"/>.
    ///     This stub must derive from a proto-generated service base class.
    /// </summary>
    public Type StubType { get; }

    /// <summary>
    ///     The proto-generated base class (e.g., <c>Greeter.GreeterBase</c>) detected via the
    ///     <see cref="BindServiceMethodAttribute"/> marker that <c>Grpc.Tools</c> stamps on
    ///     generated service bases.
    /// </summary>
    public Type ProtoServiceBase { get; }

    /// <summary>
    ///     The unary RPC methods discovered on <see cref="ProtoServiceBase"/> that will be
    ///     overridden in the generated wrapper.
    /// </summary>
    public IReadOnlyList<MethodInfo> UnaryMethods { get; }

    /// <summary>
    ///     The C# identifier used for the generated wrapper type.
    /// </summary>
    public string TypeName { get; }

    public GrpcServiceChain(Type stubType, GrpcGraph parent)
    {
        _parent = parent ?? throw new ArgumentNullException(nameof(parent));
        StubType = stubType ?? throw new ArgumentNullException(nameof(stubType));

        ProtoServiceBase = FindProtoServiceBase(stubType)
            ?? throw new InvalidOperationException(
                $"Type {stubType.FullNameInCode()} is marked as a proto-first Wolverine gRPC service, but no proto-generated base class was found in its inheritance chain. "
                + "The stub must derive from a class carrying [BindServiceMethod] (generated by Grpc.Tools from a .proto file).");

        SupportedMethods = DiscoverSupportedMethods(ProtoServiceBase).ToArray();
        AssertNoUnsupportedStreamingKinds(stubType, SupportedMethods);

        UnaryMethods = SupportedMethods
            .Where(m => m.Kind == GrpcMethodKind.Unary)
            .Select(m => m.Method)
            .ToArray();
        ServerStreamingMethods = SupportedMethods
            .Where(m => m.Kind == GrpcMethodKind.ServerStreaming)
            .Select(m => m.Method)
            .ToArray();

        ProtoServiceName = ResolveProtoServiceName(ProtoServiceBase);
        TypeName = ProtoServiceName + "GrpcHandler";
        Description = $"Generated proto-first gRPC service wrapper for {stubType.FullNameInCode()} (proto base: {ProtoServiceBase.FullNameInCode()})";
    }

    /// <summary>
    ///     All supported RPC methods Wolverine will override on the generated wrapper.
    /// </summary>
    public IReadOnlyList<GrpcRpcMethod> SupportedMethods { get; }

    /// <summary>
    ///     Server-streaming RPC methods (<c>Task Name(TRequest, IServerStreamWriter&lt;TResponse&gt;, ServerCallContext)</c>)
    ///     that forward each streamed item to <see cref="IMessageBus.StreamAsync{T}"/>.
    /// </summary>
    public IReadOnlyList<MethodInfo> ServerStreamingMethods { get; }

    /// <summary>
    ///     The proto service name (e.g., <c>Greeter</c>) — used to derive the generated type's name
    ///     as <c>{ProtoServiceName}GrpcHandler</c>. This is the stable identity of the service in
    ///     the wire protocol and tooling, not the user's stub class name.
    /// </summary>
    public string ProtoServiceName { get; }

    public override string Description { get; }

    public override MiddlewareScoping Scoping => MiddlewareScoping.Grpc;

    public override IdempotencyStyle Idempotency { get; set; } = IdempotencyStyle.None;

    /// <summary>
    ///     The runtime <see cref="Type"/> of the generated wrapper once compiled. Null before compilation.
    /// </summary>
    public Type? GeneratedType => _generatedRuntimeType;

    internal string? SourceCode => _generatedType?.SourceCode;

    public override void ApplyParameterMatching(MethodCall call)
    {
        // no-op: proto-first chains don't route through MethodCall parameter matching
    }

    public override bool TryInferMessageIdentity(out PropertyInfo? property)
    {
        property = null;
        return false;
    }

    public override bool HasAttribute<T>()
    {
        return StubType.HasAttribute<T>();
    }

    public override Type? InputType() => null;

    public override bool ShouldFlushOutgoingMessages() => false;

    public override bool RequiresOutbox() => false;

    public override MethodCall[] HandlerCalls() => [];

    public override bool TryFindVariable(string valueName, ValueSource source, Type valueType, out Variable variable)
    {
        variable = default!;
        return false;
    }

    public override Frame[] AddStopConditionIfNull(Variable variable) => [];

    public override void UseForResponse(MethodCall methodCall)
    {
        // no-op: proto-first chains don't synthesize response variables via MethodCall.
    }

    string ICodeFile.FileName => TypeName;

    void ICodeFile.AssembleTypes(GeneratedAssembly assembly)
    {
        if (_generatedType != null) return;

        assembly.ReferenceAssembly(StubType.Assembly);
        assembly.ReferenceAssembly(ProtoServiceBase.Assembly);
        assembly.ReferenceAssembly(typeof(IMessageBus).Assembly);
        assembly.ReferenceAssembly(typeof(ServerCallContext).Assembly);

        _generatedType = assembly.AddType(TypeName, StubType);

        var busField = new InjectedField(typeof(IMessageBus), "bus");
        _generatedType.AllInjectedFields.Add(busField);

        foreach (var rpc in SupportedMethods)
        {
            var generatedMethod = _generatedType.MethodFor(rpc.Method.Name);

            switch (rpc.Kind)
            {
                case GrpcMethodKind.Unary:
                    generatedMethod.Frames.Add(new ForwardUnaryToMessageBusFrame(rpc.Method, busField));
                    break;

                case GrpcMethodKind.ServerStreaming:
                    generatedMethod.AsyncMode = AsyncMode.AsyncTask;
                    generatedMethod.Frames.Add(new ForwardServerStreamToMessageBusFrame(rpc.Method, busField));
                    break;
            }
        }
    }

    Task<bool> ICodeFile.AttachTypes(GenerationRules rules, Assembly assembly, IServiceProvider? services,
        string containingNamespace)
    {
        var found = this.As<ICodeFile>().AttachTypesSynchronously(rules, assembly, services, containingNamespace);
        return Task.FromResult(found);
    }

    bool ICodeFile.AttachTypesSynchronously(GenerationRules rules, Assembly assembly, IServiceProvider? services,
        string containingNamespace)
    {
        Debug.WriteLine(_generatedType?.SourceCode);

        _generatedRuntimeType = assembly.ExportedTypes.FirstOrDefault(x => x.Name == TypeName)
                                ?? assembly.GetTypes().FirstOrDefault(x => x.Name == TypeName);

        return _generatedRuntimeType != null;
    }

    /// <summary>
    ///     Derives the proto service name from the proto-generated base class. Grpc.Tools emits
    ///     the abstract base (<c>{Service}Base</c>) nested inside a non-generic static class named
    ///     after the service (<c>{Service}</c>), so <see cref="Type.DeclaringType"/> is the preferred
    ///     source of truth. If there's no declaring type (unusual layouts), fall back to stripping
    ///     the conventional <c>Base</c> suffix.
    /// </summary>
    public static string ResolveProtoServiceName(Type protoServiceBase)
    {
        if (protoServiceBase.DeclaringType != null)
        {
            return protoServiceBase.DeclaringType.Name;
        }

        var name = protoServiceBase.Name;
        return name.EndsWith("Base", StringComparison.Ordinal)
            ? name[..^"Base".Length]
            : name;
    }

    public static Type? FindProtoServiceBase(Type stubType)
    {
        // Walk the inheritance chain and return the first ancestor carrying [BindServiceMethod].
        // That attribute is emitted by Grpc.Tools onto the abstract {Service}Base class.
        var current = stubType.BaseType;
        while (current != null && current != typeof(object))
        {
            if (current.IsDefined(typeof(BindServiceMethodAttribute), inherit: false))
            {
                return current;
            }

            current = current.BaseType;
        }

        return null;
    }

    /// <summary>
    ///     Legacy helper kept for tests and external consumers — returns only unary RPC methods.
    ///     Prefer <see cref="DiscoverSupportedMethods"/> for the full kind-aware view.
    /// </summary>
    public static IEnumerable<MethodInfo> DiscoverUnaryMethods(Type protoServiceBase)
    {
        return DiscoverSupportedMethods(protoServiceBase)
            .Where(m => m.Kind == GrpcMethodKind.Unary)
            .Select(m => m.Method);
    }

    /// <summary>
    ///     Walks the proto-generated service base, classifying each virtual RPC method by its signature.
    ///     Methods with shapes Wolverine can't yet generate (client-streaming, bidirectional-streaming)
    ///     are still returned — the chain constructor fails fast rather than silently skipping them.
    ///     Results are sorted by method name so generated source is byte-stable across runs, which
    ///     keeps diagnostic diffs and code-gen caches deterministic even when reflection reorders methods.
    /// </summary>
    public static IEnumerable<GrpcRpcMethod> DiscoverSupportedMethods(Type protoServiceBase)
    {
        var results = new List<GrpcRpcMethod>();

        foreach (var method in protoServiceBase.GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly))
        {
            if (!method.IsVirtual || method.IsFinal) continue;

            var kind = ClassifyRpcMethod(method);
            if (kind == null) continue;

            results.Add(new GrpcRpcMethod(method, kind.Value));
        }

        results.Sort(static (a, b) => string.CompareOrdinal(a.Method.Name, b.Method.Name));
        return results;
    }

    /// <summary>
    ///     Shape-check each proto RPC method against the four canonical server signatures Grpc.Tools emits.
    ///     Returns null if the method doesn't match any recognized gRPC server signature (e.g., user-added
    ///     non-RPC virtuals).
    /// </summary>
    private static GrpcMethodKind? ClassifyRpcMethod(MethodInfo method)
    {
        var parameters = method.GetParameters();

        // Unary: Task<TResponse> Name(TRequest, ServerCallContext)
        if (parameters.Length == 2
            && parameters[1].ParameterType == typeof(ServerCallContext)
            && method.ReturnType.IsGenericType
            && method.ReturnType.GetGenericTypeDefinition() == typeof(Task<>)
            && IsConcreteMessageType(parameters[0].ParameterType))
        {
            return GrpcMethodKind.Unary;
        }

        // Server-streaming: Task Name(TRequest, IServerStreamWriter<TResponse>, ServerCallContext)
        if (parameters.Length == 3
            && parameters[2].ParameterType == typeof(ServerCallContext)
            && method.ReturnType == typeof(Task)
            && IsConcreteMessageType(parameters[0].ParameterType)
            && IsGenericOf(parameters[1].ParameterType, typeof(IServerStreamWriter<>)))
        {
            return GrpcMethodKind.ServerStreaming;
        }

        // Client-streaming: Task<TResponse> Name(IAsyncStreamReader<TRequest>, ServerCallContext)
        if (parameters.Length == 2
            && parameters[1].ParameterType == typeof(ServerCallContext)
            && method.ReturnType.IsGenericType
            && method.ReturnType.GetGenericTypeDefinition() == typeof(Task<>)
            && IsGenericOf(parameters[0].ParameterType, typeof(IAsyncStreamReader<>)))
        {
            return GrpcMethodKind.ClientStreaming;
        }

        // Bidirectional: Task Name(IAsyncStreamReader<TRequest>, IServerStreamWriter<TResponse>, ServerCallContext)
        if (parameters.Length == 3
            && parameters[2].ParameterType == typeof(ServerCallContext)
            && method.ReturnType == typeof(Task)
            && IsGenericOf(parameters[0].ParameterType, typeof(IAsyncStreamReader<>))
            && IsGenericOf(parameters[1].ParameterType, typeof(IServerStreamWriter<>)))
        {
            return GrpcMethodKind.BidirectionalStreaming;
        }

        return null;
    }

    private static bool IsConcreteMessageType(Type t) => t.IsClass && !t.IsAbstract;

    private static bool IsGenericOf(Type t, Type openGeneric)
        => t.IsGenericType && t.GetGenericTypeDefinition() == openGeneric;

    private static void AssertNoUnsupportedStreamingKinds(Type stubType, IReadOnlyList<GrpcRpcMethod> methods)
    {
        var unsupported = methods
            .Where(m => m.Kind is GrpcMethodKind.ClientStreaming or GrpcMethodKind.BidirectionalStreaming)
            .ToList();

        if (unsupported.Count == 0) return;

        var detail = unsupported
            .Select(m => $"  - {m.Method.Name} ({m.Kind})")
            .Aggregate((a, b) => a + Environment.NewLine + b);

        throw new NotSupportedException(
            $"Proto-first gRPC stub {stubType.FullNameInCode()} declares RPC method(s) whose shape "
            + "Wolverine cannot yet code-generate. Supported today: unary and server-streaming. "
            + "Client-streaming and bidirectional-streaming need a request-side IAsyncEnumerable overload on IMessageBus "
            + "that has not been introduced yet."
            + Environment.NewLine
            + "Unsupported method(s):"
            + Environment.NewLine
            + detail
            + Environment.NewLine
            + "Workaround: move the affected RPC(s) into a separate service whose stub is NOT marked "
            + "[WolverineGrpcService], and implement those methods by hand (calling IMessageBus directly).");
    }
}

/// <summary>
///     Classification of a proto-generated RPC method based on its C# signature.
///     Matches the four canonical shapes that <c>Grpc.Tools</c> emits on the server base class.
/// </summary>
public enum GrpcMethodKind
{
    /// <summary>
    ///     Unary RPC: <c>Task&lt;TResponse&gt; Name(TRequest, ServerCallContext)</c>. Forwards to
    ///     <see cref="IMessageBus.InvokeAsync{T}(object, CancellationToken, TimeSpan?)"/>.
    /// </summary>
    Unary,

    /// <summary>
    ///     Server-streaming RPC: <c>Task Name(TRequest, IServerStreamWriter&lt;TResponse&gt;, ServerCallContext)</c>.
    ///     Forwards to <see cref="IMessageBus.StreamAsync{TResponse}(object, CancellationToken)"/> and pumps each
    ///     yielded item to the stream writer.
    /// </summary>
    ServerStreaming,

    /// <summary>
    ///     Client-streaming RPC: <c>Task&lt;TResponse&gt; Name(IAsyncStreamReader&lt;TRequest&gt;, ServerCallContext)</c>.
    ///     Not yet code-generated by Wolverine — detection fails fast at startup rather than silently skipping.
    /// </summary>
    ClientStreaming,

    /// <summary>
    ///     Bidirectional-streaming RPC: <c>Task Name(IAsyncStreamReader&lt;TRequest&gt;, IServerStreamWriter&lt;TResponse&gt;, ServerCallContext)</c>.
    ///     Not yet code-generated by Wolverine — detection fails fast at startup rather than silently skipping.
    /// </summary>
    BidirectionalStreaming
}

/// <summary>
///     A single proto RPC method paired with the Wolverine-recognized <see cref="GrpcMethodKind"/>.
/// </summary>
/// <param name="Method">Reflection handle to the virtual method on the proto-generated service base.</param>
/// <param name="Kind">The RPC shape Wolverine classified this method as.</param>
public readonly record struct GrpcRpcMethod(MethodInfo Method, GrpcMethodKind Kind);

/// <summary>
///     Emits <c>return _bus.InvokeAsync&lt;TResponse&gt;(request, context.CancellationToken);</c>
///     inside an override of a proto-generated unary RPC method.
/// </summary>
internal sealed class ForwardUnaryToMessageBusFrame : SyncFrame
{
    private readonly MethodInfo _rpc;
    private readonly InjectedField _busField;

    public ForwardUnaryToMessageBusFrame(MethodInfo rpc, InjectedField busField)
    {
        _rpc = rpc;
        _busField = busField;
    }

    public override void GenerateCode(GeneratedMethod method, ISourceWriter writer)
    {
        var parameters = _rpc.GetParameters();
        var requestName = ParameterName(parameters, 0);
        var contextName = ParameterName(parameters, 1);
        var responseType = _rpc.ReturnType.GetGenericArguments()[0];

        writer.Write(
            $"return {_busField.Usage}.{nameof(IMessageBus.InvokeAsync)}<{responseType.FullNameInCode()}>({requestName}, {contextName}.{nameof(ServerCallContext.CancellationToken)});");

        Next?.GenerateCode(method, writer);
    }

    // Grpc.Tools always emits parameter names, but reflection over optimized assemblies can return null.
    // A stable fallback keeps the generated source compilable even in those odd cases.
    internal static string ParameterName(ParameterInfo[] parameters, int index)
        => parameters[index].Name ?? $"arg{index}";
}

/// <summary>
///     Emits an <c>await foreach</c> loop bridging <see cref="IMessageBus.StreamAsync{T}"/> to a gRPC
///     server-streaming method's <see cref="IServerStreamWriter{T}"/>. The generated method is marked
///     <see cref="AsyncMode.AsyncTask"/> so the <c>await</c> keyword is legal in the body.
/// </summary>
internal sealed class ForwardServerStreamToMessageBusFrame : AsyncFrame
{
    private readonly MethodInfo _rpc;
    private readonly InjectedField _busField;

    public ForwardServerStreamToMessageBusFrame(MethodInfo rpc, InjectedField busField)
    {
        _rpc = rpc;
        _busField = busField;
    }

    public override void GenerateCode(GeneratedMethod method, ISourceWriter writer)
    {
        var parameters = _rpc.GetParameters();
        var requestName = ForwardUnaryToMessageBusFrame.ParameterName(parameters, 0);
        var streamWriterName = ForwardUnaryToMessageBusFrame.ParameterName(parameters, 1);
        var contextName = ForwardUnaryToMessageBusFrame.ParameterName(parameters, 2);

        // IServerStreamWriter<TResponse> → TResponse
        var responseType = parameters[1].ParameterType.GetGenericArguments()[0];
        var cancellation = $"{contextName}.{nameof(ServerCallContext.CancellationToken)}";

        writer.Write(
            $"BLOCK:await foreach (var item in {_busField.Usage}.{nameof(IMessageBus.StreamAsync)}<{responseType.FullNameInCode()}>({requestName}, {cancellation}))");
        writer.Write($"await {streamWriterName}.WriteAsync(item, {cancellation});");
        writer.FinishBlock();

        Next?.GenerateCode(method, writer);
    }
}
