using System.ServiceModel;
using Grpc.Core;
using Grpc.Core.Interceptors;
using Grpc.Net.Client;
using Grpc.Net.ClientFactory;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Options;
using ProtoBuf.Grpc.Client;

namespace Wolverine.Grpc.Client;

/// <summary>
///     Extension methods for registering Wolverine-flavored typed gRPC clients.
/// </summary>
/// <remarks>
///     <para>
///         <see cref="AddWolverineGrpcClient{TClient}"/> is a thin Wolverine wrapper over
///         <c>Grpc.Net.ClientFactory.AddGrpcClient&lt;T&gt;()</c> — the Microsoft client factory
///         remains the substrate for proto-first typed clients, and Wolverine simply layers three
///         conveniences on top:
///         <list type="number">
///             <item>
///                 <see cref="WolverineGrpcClientPropagationInterceptor"/> — stamps
///                 <c>correlation-id</c>, <c>tenant-id</c>, <c>parent-id</c>, <c>conversation-id</c>
///                 and <c>message-id</c> headers on outgoing calls when an <see cref="IMessageContext"/>
///                 is resolvable from the current DI scope. The wire vocabulary matches every other
///                 Wolverine transport via <see cref="EnvelopeConstants"/>.
///             </item>
///             <item>
///                 <see cref="WolverineGrpcClientExceptionInterceptor"/> — translates an incoming
///                 <see cref="RpcException"/> into a typed .NET exception using the shared
///                 <see cref="WolverineGrpcExceptionMapper.MapToException"/> table. The inverse of
///                 the server-side <see cref="WolverineGrpcExceptionInterceptor"/>.
///             </item>
///             <item>
///                 <see cref="WolverineGrpcClientBuilder.ConfigureChannel"/> — an escape hatch to
///                 raw <see cref="GrpcChannelOptions"/>. Wolverine wraps, never replaces, the
///                 underlying vendor API.
///             </item>
///         </list>
///     </para>
///     <para>
///         Code-first (<c>[ServiceContract]</c>) typed clients consumed via <c>protobuf-net.Grpc</c>
///         do not ride on <c>IHttpClientFactory</c>, so the registration path for them is handled by
///         Wolverine's own factory — <see cref="WolverineGrpcCodeFirstChannelFactory"/>. Users do not
///         need to care which path is chosen: <see cref="AddWolverineGrpcClient{TClient}"/> detects
///         the contract style automatically.
///     </para>
/// </remarks>
public static class WolverineGrpcClientExtensions
{
    /// <summary>
    ///     Register a typed gRPC client with Wolverine envelope-header propagation and
    ///     <see cref="RpcException"/> → typed-exception mapping.
    /// </summary>
    /// <typeparam name="TClient">
    ///     Either a concrete proto-first client (e.g. <c>Greeter.GreeterClient</c> generated by
    ///     <c>Grpc.Tools</c>) or a code-first <c>[ServiceContract]</c> interface consumed by
    ///     <c>protobuf-net.Grpc</c>.
    /// </typeparam>
    /// <param name="services">The service collection.</param>
    /// <param name="configure">
    ///     Callback that configures <see cref="WolverineGrpcClientOptions"/> — at minimum set
    ///     <see cref="WolverineGrpcClientOptions.Address"/>.
    /// </param>
    /// <returns>
    ///     A <see cref="WolverineGrpcClientBuilder"/> that allows chaining
    ///     <see cref="WolverineGrpcClientBuilder.ConfigureChannel"/> and, for proto-first
    ///     registrations, direct access to the underlying <see cref="IHttpClientBuilder"/>.
    /// </returns>
    public static WolverineGrpcClientBuilder AddWolverineGrpcClient<TClient>(
        this IServiceCollection services,
        Action<WolverineGrpcClientOptions>? configure = null)
        where TClient : class
    {
        ArgumentNullException.ThrowIfNull(services);

        var name = typeof(TClient).FullName!;

        if (configure != null)
        {
            services.Configure(name, configure);
        }

        services.AddOptions<WolverineGrpcClientOptions>(name);
        services.AddOptions<WolverineGrpcCodeFirstClientOptions>(name);

        if (IsCodeFirstContract(typeof(TClient)))
        {
            services.TryAddSingleton<WolverineGrpcCodeFirstChannelFactory>();

            services.AddTransient(sp => ResolveCodeFirstClient<TClient>(sp, name));

            return new WolverineGrpcClientBuilder(
                services,
                name,
                WolverineGrpcClientKind.CodeFirst,
                httpClientBuilder: null);
        }

        // Proto-first: delegate to Microsoft's factory. The IServiceProvider overload of
        // AddGrpcClient<T>() lets us read WolverineGrpcClientOptions.Address at DI-resolution
        // time instead of at registration time (which would require BuildServiceProvider —
        // an anti-pattern).
        var httpBuilder = services.AddGrpcClient<TClient>(name, (sp, o) =>
        {
            var monitor = sp.GetRequiredService<IOptionsMonitor<WolverineGrpcClientOptions>>();
            var opts = monitor.Get(name);
            if (opts.Address != null)
            {
                o.Address = opts.Address;
            }
        });

        // Ordering: exception interceptor is registered FIRST so it sits outermost in the call
        // chain. If the user composes Polly / AddStandardResilienceHandler() around the HTTP
        // handler pipeline, retries fire INSIDE our RpcException catch, preserving retry
        // semantics. Documented in WolverineGrpcClientExceptionInterceptor.
        httpBuilder.AddInterceptor(sp => new WolverineGrpcClientExceptionInterceptor(
            sp.GetRequiredService<IOptionsMonitor<WolverineGrpcClientOptions>>(),
            name));

        httpBuilder.AddInterceptor(sp => new WolverineGrpcClientPropagationInterceptor(
            sp,
            sp.GetRequiredService<IOptionsMonitor<WolverineGrpcClientOptions>>(),
            name));

        return new WolverineGrpcClientBuilder(
            services,
            name,
            WolverineGrpcClientKind.ProtoFirst,
            httpBuilder);
    }

    /// <summary>
    ///     Detects the code-first contract style: a <c>[ServiceContract]</c>-annotated interface
    ///     consumed by <c>protobuf-net.Grpc</c>. Classes (proto-first generated clients) are not
    ///     decorated with this attribute.
    /// </summary>
    internal static bool IsCodeFirstContract(Type t)
    {
        return t.IsInterface && t.IsDefined(typeof(ServiceContractAttribute), inherit: true);
    }

    private static TClient ResolveCodeFirstClient<TClient>(IServiceProvider sp, string name)
        where TClient : class
    {
        var monitor = sp.GetRequiredService<IOptionsMonitor<WolverineGrpcClientOptions>>();
        var opts = monitor.Get(name);

        if (opts.Address == null)
        {
            throw new InvalidOperationException(
                $"Wolverine gRPC client for '{typeof(TClient).FullName}' is missing an Address. "
                + "Set WolverineGrpcClientOptions.Address when calling AddWolverineGrpcClient<T>(...).");
        }

        var factory = sp.GetRequiredService<WolverineGrpcCodeFirstChannelFactory>();
        var channel = factory.GetOrCreate(name, opts.Address);

        // Ordering: Intercept stacks last-applied-outermost. Apply propagation first so exception
        // ends up outermost. See WolverineGrpcClientExceptionInterceptor for why.
        var propagation = new WolverineGrpcClientPropagationInterceptor(sp, monitor, name);
        var exception = new WolverineGrpcClientExceptionInterceptor(monitor, name);

        CallInvoker invoker = channel.Intercept(propagation).Intercept(exception);

        return invoker.CreateGrpcService<TClient>();
    }
}
