using Grpc.Net.Client;
using Grpc.Net.ClientFactory;
using Microsoft.Extensions.DependencyInjection;

namespace Wolverine.Grpc.Client;

/// <summary>
///     Fluent builder returned by
///     <see cref="WolverineGrpcClientExtensions.AddWolverineGrpcClient{T}(IServiceCollection,Action{WolverineGrpcClientOptions}?)"/>.
///     Exposes the escape hatch to the underlying
///     <see cref="GrpcChannelOptions"/> and, when the typed client is proto-first, access to the
///     underlying <see cref="IHttpClientBuilder"/> so standard handlers (Polly, logging, authentication)
///     can be composed.
/// </summary>
/// <remarks>
///     <para>
///         Wolverine's rule is to <em>wrap, never replace</em> vendor APIs. This builder is the
///         seam that keeps <c>Grpc.Net.Client</c> / <c>IHttpClientFactory</c> knobs reachable — any
///         configuration expressible directly on <see cref="IHttpClientBuilder"/> stays expressible
///         through <see cref="HttpClientBuilder"/>.
///     </para>
///     <para>
///         For code-first (<c>[ServiceContract]</c>) registrations there is no
///         <see cref="IHttpClientBuilder"/> — <see cref="HttpClientBuilder"/> is <c>null</c> in that
///         case because <c>protobuf-net.Grpc</c> does not ride on <c>IHttpClientFactory</c>. Callers
///         who need Polly or custom handlers must use proto-first for that client.
///     </para>
/// </remarks>
public sealed class WolverineGrpcClientBuilder
{
    internal WolverineGrpcClientBuilder(
        IServiceCollection services,
        string name,
        WolverineGrpcClientKind kind,
        IHttpClientBuilder? httpClientBuilder)
    {
        Services = services;
        Name = name;
        Kind = kind;
        HttpClientBuilder = httpClientBuilder;
    }

    /// <summary>
    ///     The underlying <see cref="IServiceCollection"/> — exposed so additional typed extensions
    ///     can layer on.
    /// </summary>
    public IServiceCollection Services { get; }

    /// <summary>
    ///     The logical name of the typed client. For proto-first clients this matches the name
    ///     <c>AddGrpcClient&lt;T&gt;()</c> registers against <see cref="GrpcClientFactoryOptions"/>.
    /// </summary>
    public string Name { get; }

    /// <summary>
    ///     Whether the registration routes through Microsoft's <c>AddGrpcClient&lt;T&gt;()</c>
    ///     (<see cref="WolverineGrpcClientKind.ProtoFirst"/>) or through Wolverine's own
    ///     <c>protobuf-net.Grpc</c> factory wiring (<see cref="WolverineGrpcClientKind.CodeFirst"/>).
    /// </summary>
    public WolverineGrpcClientKind Kind { get; }

    /// <summary>
    ///     The underlying <see cref="IHttpClientBuilder"/> for proto-first registrations, or
    ///     <c>null</c> for code-first registrations.
    /// </summary>
    public IHttpClientBuilder? HttpClientBuilder { get; }

    /// <summary>
    ///     Escape hatch to the underlying <see cref="GrpcChannelOptions"/>. Equivalent to calling
    ///     <c>.ConfigureChannel(...)</c> on the Microsoft proto-first builder. For code-first
    ///     registrations the callback is applied when Wolverine constructs the internal
    ///     <see cref="GrpcChannel"/> for the named client.
    /// </summary>
    public WolverineGrpcClientBuilder ConfigureChannel(Action<GrpcChannelOptions> configure)
    {
        ArgumentNullException.ThrowIfNull(configure);

        if (Kind == WolverineGrpcClientKind.ProtoFirst)
        {
            Services.Configure<GrpcClientFactoryOptions>(Name, opts =>
            {
                opts.ChannelOptionsActions.Add(configure);
            });
        }
        else
        {
            Services.Configure<WolverineGrpcCodeFirstClientOptions>(Name, opts =>
            {
                opts.ChannelConfigurations.Add(configure);
            });
        }

        return this;
    }
}

/// <summary>
///     Discriminates the two registration paths Wolverine supports for typed gRPC clients.
/// </summary>
public enum WolverineGrpcClientKind
{
    /// <summary>
    ///     Proto-first: <c>T</c> is a concrete client class generated by <c>Grpc.Tools</c>
    ///     (e.g. <c>Greeter.GreeterClient</c>). Registered through <c>AddGrpcClient&lt;T&gt;()</c>.
    /// </summary>
    ProtoFirst,

    /// <summary>
    ///     Code-first: <c>T</c> is a <c>[ServiceContract]</c>-annotated interface consumed via
    ///     <c>protobuf-net.Grpc</c>'s <c>ClientFactory.Create&lt;T&gt;(CallInvoker)</c>.
    /// </summary>
    CodeFirst
}
