// <auto-generated/>

namespace Internal.Generated.WolverineHandlers

open System
open System.Threading
open System.Threading.Tasks
open Wolverine.Marten.Publishing
open Wolverine.Runtime
open Wolverine.Runtime.Handlers

type IncrementCounterHandler805386214(outboxedSessionFactory: Wolverine.Marten.Publishing.OutboxedSessionFactory) =
    inherit Wolverine.Runtime.Handlers.MessageHandler()
    let _outboxedSessionFactory = outboxedSessionFactory

    override this.HandleAsync(context: Wolverine.Runtime.MessageContext, cancellation: System.Threading.CancellationToken) : System.Threading.Tasks.Task =
        task {
            // Building the Marten session
            use documentSession = _outboxedSessionFactory.OpenSession(context)
            // The actual message body
            let incrementCounter = context.Envelope.Message :?> WolverineMartenAggregateFSharpSample.IncrementCounter

            let counter_Id = incrementCounter.CounterId
            // Application-specific Open Telemetry auditing
            if not (isNull System.Diagnostics.Activity.Current) then
                System.Diagnostics.Activity.Current.SetTag("counter.id", incrementCounter.CounterId) |> ignore
            if not (isNull System.Diagnostics.Activity.Current) then
                System.Diagnostics.Activity.Current.SetTag("message.handler", "WolverineMartenAggregateFSharpSample.IncrementHandler") |> ignore
                System.Diagnostics.Activity.Current.SetTag("handler.type", "WolverineMartenAggregateFSharpSample.IncrementHandler") |> ignore
            // Loading Marten aggregate as part of the aggregate handler workflow
            let! eventStreamOfCounter = documentSession.Events.FetchForWriting<WolverineMartenAggregateFSharpSample.Counter>(counter_Id, cancellation)
            if not (isNull System.Diagnostics.Activity.Current) then System.Diagnostics.Activity.Current.SetTag("wolverine.stream.id", counter_Id.ToString()) |> ignore
            if not (isNull System.Diagnostics.Activity.Current) then System.Diagnostics.Activity.Current.SetTag("wolverine.stream.type", "WolverineMartenAggregateFSharpSample.Counter") |> ignore
            
            // The actual message execution
            let outgoing1 = WolverineMartenAggregateFSharpSample.IncrementHandler.Handle(incrementCounter, eventStreamOfCounter.Aggregate)

            eventStreamOfCounter.AppendOne(outgoing1)
            
            // Save all pending changes to this Marten session
            do! documentSession.SaveChangesAsync(cancellation)

            
            // Have to flush outgoing messages just in case Marten did nothing because of https://github.com/JasperFx/wolverine/issues/536
            do! context.FlushOutgoingMessagesAsync()

        }

