// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using QuickType;
//
//    var azureServiceBusEmulatorConfig = AzureServiceBusEmulatorConfig.FromJson(jsonString);
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8603

namespace Wolverine.AzureServiceBus.Emulator
{
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;

    /// <summary>
    /// Main user configuration object
    /// </summary>
    public partial class AzureServiceBusEmulatorConfig
    {
        [JsonPropertyName("UserConfig")]
        public UserConfig UserConfig { get; set; }
    }

    public partial class UserConfig
    {
        /// <summary>
        /// Configuration for logging is defined here
        /// </summary>
        [JsonPropertyName("Logging")]
        public Logging Logging { get; set; }

        /// <summary>
        /// Namespace configuration is defined here
        /// </summary>
        [JsonPropertyName("Namespaces")]
        public List<Namespace> Namespaces { get; set; }
    }

    /// <summary>
    /// Configuration for logging is defined here
    /// </summary>
    public partial class Logging
    {
        /// <summary>
        /// Types of logging
        /// </summary>
        [JsonPropertyName("Type")]
        public TypeEnum Type { get; set; }
    }

    public partial class Namespace
    {
        /// <summary>
        /// Name of the namespace
        /// </summary>
        [JsonPropertyName("Name")]
        public Name Name { get; set; }

        /// <summary>
        /// Queue configuration is defined here. Max Queues + Topics per namespace is 50
        /// </summary>
        [JsonPropertyName("Queues")]
        public List<Queue> Queues { get; set; }

        /// <summary>
        /// Topic configuration is defined here. Max Queues + Topics per namespace is 50
        /// </summary>
        [JsonPropertyName("Topics")]
        public List<Topic> Topics { get; set; }
    }

    public partial class Queue
    {
        /// <summary>
        /// Name of the queue
        /// </summary>
        [JsonPropertyName("Name")]
        public string Name { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("Properties")]
        public QueueProperties Properties { get; set; }
    }

    public partial class QueueProperties
    {
        /// <summary>
        /// Indicates whether this queue has dead letter support when a message expires
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("DeadLetteringOnMessageExpiration")]
        public bool? DeadLetteringOnMessageExpiration { get; set; }

        /// <summary>
        /// Specifies the default time-to-live for messages. Must be a valid ISO 8601 datetime
        /// string. The default value is PT1H (1 hour), the minimum value is PT5M (5 minutes) and the
        /// maximum value is PT1H (1 hour).
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("DefaultMessageTimeToLive")]
        public string DefaultMessageTimeToLive { get; set; }

        /// <summary>
        /// Specifies the time window for duplicate detection. Must be a valid ISO 8601 datetime
        /// string. The default value is PT20S (20 seconds), the minimum value is PT5S (5 seconds)
        /// and the maximum value is PT5M (5 minutes).
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("DuplicateDetectionHistoryTimeWindow")]
        public string DuplicateDetectionHistoryTimeWindow { get; set; }

        /// <summary>
        /// Forward dead lettered messages to
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("ForwardDeadLetteredMessagesTo")]
        public string ForwardDeadLetteredMessagesTo { get; set; }

        /// <summary>
        /// Forward to
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("ForwardTo")]
        public string ForwardTo { get; set; }

        /// <summary>
        /// Specifies the duration of a peek lock. Must be a valid ISO 8601 datetime string. The
        /// default value is PT1M (1 minute), the minimum value is PT5S (5 seconds) and the maximum
        /// value is PT5M (5 minutes).
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("LockDuration")]
        public string LockDuration { get; set; }

        /// <summary>
        /// Specifies the maximum number of times a message delivery is attempted before it is moved
        /// to the dead-letter queue.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("MaxDeliveryCount")]
        public long? MaxDeliveryCount { get; set; }

        /// <summary>
        /// Indicates whether this queue requires duplicate detection
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("RequiresDuplicateDetection")]
        public bool? RequiresDuplicateDetection { get; set; }

        /// <summary>
        /// Indicates whether this queue requires session support
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("RequiresSession")]
        public bool? RequiresSession { get; set; }
    }

    public partial class Topic
    {
        /// <summary>
        /// Name of the topic
        /// </summary>
        [JsonPropertyName("Name")]
        public string Name { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("Properties")]
        public TopicProperties Properties { get; set; }

        /// <summary>
        /// Subscription configuration is defined here
        /// </summary>
        [JsonPropertyName("Subscriptions")]
        public List<Subscription> Subscriptions { get; set; }
    }

    public partial class TopicProperties
    {
        /// <summary>
        /// Specifies the default time-to-live for messages. Must be a valid ISO 8601 datetime
        /// string. The default value is PT1H (1 hour), the minimum value is PT5M (5 minutes) and the
        /// maximum value is PT1H (1 hour).
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("DefaultMessageTimeToLive")]
        public string DefaultMessageTimeToLive { get; set; }

        /// <summary>
        /// Specifies the time window for duplicate detection. Must be a valid ISO 8601 datetime
        /// string. The default value is PT20S (20 seconds), the minimum value is PT5S (5 seconds)
        /// and the maximum value is PT5M (5 minutes).
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("DuplicateDetectionHistoryTimeWindow")]
        public string DuplicateDetectionHistoryTimeWindow { get; set; }

        /// <summary>
        /// Indicates whether this topic requires duplicate detection
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("RequiresDuplicateDetection")]
        public bool? RequiresDuplicateDetection { get; set; }
    }

    public partial class Subscription
    {
        /// <summary>
        /// Name of the subscription
        /// </summary>
        [JsonPropertyName("Name")]
        public string Name { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("Properties")]
        public SubscriptionProperties Properties { get; set; }

        /// <summary>
        /// Rule configuration is defined here. Maximum Rules per topic is 1000
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("Rules")]
        public List<Rule> Rules { get; set; }
    }

    public partial class SubscriptionProperties
    {
        /// <summary>
        /// Indicates whether this subscription has dead letter support when a message expires
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("DeadLetteringOnMessageExpiration")]
        public bool? DeadLetteringOnMessageExpiration { get; set; }

        /// <summary>
        /// Specifies the default time-to-live for messages. Must be a valid ISO 8601 datetime
        /// string. The default value is PT1H (1 hour), the minimum value is PT5M (5 minutes) and the
        /// maximum value is PT1H (1 hour).
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("DefaultMessageTimeToLive")]
        public string DefaultMessageTimeToLive { get; set; }

        /// <summary>
        /// Forward dead lettered messages to
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("ForwardDeadLetteredMessagesTo")]
        public string ForwardDeadLetteredMessagesTo { get; set; }

        /// <summary>
        /// Forward to
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("ForwardTo")]
        public string ForwardTo { get; set; }

        /// <summary>
        /// Specifies the duration of a peek lock. Must be a valid ISO 8601 datetime string. The
        /// default value is PT1M (1 minute), the minimum value is PT1M (1 minute) and the maximum
        /// value is PT5M (5 minutes).
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("LockDuration")]
        public string LockDuration { get; set; }

        /// <summary>
        /// Specifies the maximum number of times a message delivery is attempted before it is moved
        /// to the dead-letter queue.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("MaxDeliveryCount")]
        public long? MaxDeliveryCount { get; set; }

        /// <summary>
        /// Indicates whether this queue requires session support
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("RequiresSession")]
        public bool? RequiresSession { get; set; }
    }

    public partial class Rule
    {
        /// <summary>
        /// Name of the rule
        /// </summary>
        [JsonPropertyName("Name")]
        public string Name { get; set; }

        [JsonPropertyName("Properties")]
        public RuleProperties Properties { get; set; }
    }

    public partial class RuleProperties
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("Action")]
        public Action Action { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("CorrelationFilter")]
        public CorrelationFilter CorrelationFilter { get; set; }

        /// <summary>
        /// Type of filter
        /// </summary>
        [JsonPropertyName("FilterType")]
        public FilterType FilterType { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("SqlFilter")]
        public SqlFilter SqlFilter { get; set; }
    }

    public partial class Action
    {
        /// <summary>
        /// SQL expression for the action
        /// </summary>
        [JsonPropertyName("SqlExpression")]
        public string SqlExpression { get; set; }
    }

    public partial class CorrelationFilter
    {
        /// <summary>
        /// Content type
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("ContentType")]
        public string ContentType { get; set; }

        /// <summary>
        /// Correlation id
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("CorrelationId")]
        public string CorrelationId { get; set; }

        /// <summary>
        /// Label
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("Label")]
        public string Label { get; set; }

        /// <summary>
        /// Message id
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("MessageId")]
        public string MessageId { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("Properties")]
        public Dictionary<string, object> Properties { get; set; }

        /// <summary>
        /// Reply to
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("ReplyTo")]
        public string ReplyTo { get; set; }

        /// <summary>
        /// Reply to session id
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("ReplyToSessionId")]
        public string ReplyToSessionId { get; set; }

        /// <summary>
        /// Session id
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("SessionId")]
        public string SessionId { get; set; }

        /// <summary>
        /// To
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("To")]
        public string To { get; set; }
    }

    public partial class SqlFilter
    {
        /// <summary>
        /// SQL expression for the filter
        /// </summary>
        [JsonPropertyName("SqlExpression")]
        public string SqlExpression { get; set; }
    }

    /// <summary>
    /// Types of logging
    /// </summary>
    public enum TypeEnum { Console, ConsoleFile, File, FileConsole };

    /// <summary>
    /// Name of the namespace
    /// </summary>
    public enum Name { Sbemulatorns };

    /// <summary>
    /// Type of filter
    /// </summary>
    public enum FilterType { Correlation, Sql };

    public partial class AzureServiceBusEmulatorConfig
    {
        public static AzureServiceBusEmulatorConfig FromJson(string json) => JsonSerializer.Deserialize<AzureServiceBusEmulatorConfig>(json, Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this AzureServiceBusEmulatorConfig self) => JsonSerializer.Serialize(self, Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
        {
            Converters =
            {
                TypeEnumConverter.Singleton,
                NameConverter.Singleton,
                FilterTypeConverter.Singleton,
                new DateOnlyConverter(),
                new TimeOnlyConverter(),
                IsoDateTimeOffsetConverter.Singleton
            },
        };
    }

    internal class TypeEnumConverter : JsonConverter<TypeEnum>
    {
        public override bool CanConvert(Type t) => t == typeof(TypeEnum);

        public override TypeEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "Console":
                    return TypeEnum.Console;
                case "Console,File":
                    return TypeEnum.ConsoleFile;
                case "File":
                    return TypeEnum.File;
                case "File,Console":
                    return TypeEnum.FileConsole;
            }
            throw new Exception("Cannot unmarshal type TypeEnum");
        }

        public override void Write(Utf8JsonWriter writer, TypeEnum value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case TypeEnum.Console:
                    JsonSerializer.Serialize(writer, "Console", options);
                    return;
                case TypeEnum.ConsoleFile:
                    JsonSerializer.Serialize(writer, "Console,File", options);
                    return;
                case TypeEnum.File:
                    JsonSerializer.Serialize(writer, "File", options);
                    return;
                case TypeEnum.FileConsole:
                    JsonSerializer.Serialize(writer, "File,Console", options);
                    return;
            }
            throw new Exception("Cannot marshal type TypeEnum");
        }

        public static readonly TypeEnumConverter Singleton = new TypeEnumConverter();
    }

    internal class NameConverter : JsonConverter<Name>
    {
        public override bool CanConvert(Type t) => t == typeof(Name);

        public override Name Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            if (value == "sbemulatorns")
            {
                return Name.Sbemulatorns;
            }
            throw new Exception("Cannot unmarshal type Name");
        }

        public override void Write(Utf8JsonWriter writer, Name value, JsonSerializerOptions options)
        {
            if (value == Name.Sbemulatorns)
            {
                JsonSerializer.Serialize(writer, "sbemulatorns", options);
                return;
            }
            throw new Exception("Cannot marshal type Name");
        }

        public static readonly NameConverter Singleton = new NameConverter();
    }

    internal class FilterTypeConverter : JsonConverter<FilterType>
    {
        public override bool CanConvert(Type t) => t == typeof(FilterType);

        public override FilterType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "Correlation":
                    return FilterType.Correlation;
                case "Sql":
                    return FilterType.Sql;
            }
            throw new Exception("Cannot unmarshal type FilterType");
        }

        public override void Write(Utf8JsonWriter writer, FilterType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case FilterType.Correlation:
                    JsonSerializer.Serialize(writer, "Correlation", options);
                    return;
                case FilterType.Sql:
                    JsonSerializer.Serialize(writer, "Sql", options);
                    return;
            }
            throw new Exception("Cannot marshal type FilterType");
        }

        public static readonly FilterTypeConverter Singleton = new FilterTypeConverter();
    }
    
    public class DateOnlyConverter : JsonConverter<DateOnly>
    {
        private readonly string serializationFormat;
        public DateOnlyConverter() : this(null) { }

        public DateOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "yyyy-MM-dd";
        }

        public override DateOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return DateOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, DateOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    public class TimeOnlyConverter : JsonConverter<TimeOnly>
    {
        private readonly string serializationFormat;

        public TimeOnlyConverter() : this(null) { }

        public TimeOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "HH:mm:ss.fff";
        }

        public override TimeOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return TimeOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, TimeOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    internal class IsoDateTimeOffsetConverter : JsonConverter<DateTimeOffset>
    {
        public override bool CanConvert(Type t) => t == typeof(DateTimeOffset);

        private const string DefaultDateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK";

        private DateTimeStyles _dateTimeStyles = DateTimeStyles.RoundtripKind;
        private string? _dateTimeFormat;
        private CultureInfo? _culture;

        public DateTimeStyles DateTimeStyles
        {
                get => _dateTimeStyles;
                set => _dateTimeStyles = value;
        }

        public string? DateTimeFormat
        {
                get => _dateTimeFormat ?? string.Empty;
                set => _dateTimeFormat = (string.IsNullOrEmpty(value)) ? null : value;
        }

        public CultureInfo Culture
        {
                get => _culture ?? CultureInfo.CurrentCulture;
                set => _culture = value;
        }

        public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
        {
                string text;


                if ((_dateTimeStyles & DateTimeStyles.AdjustToUniversal) == DateTimeStyles.AdjustToUniversal
                        || (_dateTimeStyles & DateTimeStyles.AssumeUniversal) == DateTimeStyles.AssumeUniversal)
                {
                        value = value.ToUniversalTime();
                }

                text = value.ToString(_dateTimeFormat ?? DefaultDateTimeFormat, Culture);

                writer.WriteStringValue(text);
        }

        public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                string? dateText = reader.GetString();

                if (string.IsNullOrEmpty(dateText) == false)
                {
                        if (!string.IsNullOrEmpty(_dateTimeFormat))
                        {
                                return DateTimeOffset.ParseExact(dateText, _dateTimeFormat, Culture, _dateTimeStyles);
                        }
                        else
                        {
                                return DateTimeOffset.Parse(dateText, Culture, _dateTimeStyles);
                        }
                }
                else
                {
                        return default(DateTimeOffset);
                }
        }


        public static readonly IsoDateTimeOffsetConverter Singleton = new IsoDateTimeOffsetConverter();
    }
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8603
