<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>SQL Server database LOB backend for the Wolverine Claim Check pattern</Description>
        <PackageId>WolverineFx.ClaimCheck.SqlServer</PackageId>
        <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
        <GenerateAssemblyCopyrightAttribute>false</GenerateAssemblyCopyrightAttribute>
        <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
        <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
        <GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Wolverine\Wolverine.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Data.SqlClient" />
    </ItemGroup>

</Project>
