name: efcore

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  config: Release
  disable_test_parallelization: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Run EF Core Tests
        run: ./build.sh CIEfCore --framework net9.0

      - name: Stop containers
        if: always()
        run: docker compose down
